#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=19

# A database URL contains a password. Never honor caller-supplied shell tracing
# while this wizard handles secrets.
set +x

# The template defaults to .env. This deployment deliberately uses an ignored,
# environment-specific operator record unless the caller supplied ENV_FILE.
if [[ "$ENV_FILE" == ".env" ]]; then
  ENV_FILE=".env.staging"
fi
umask 077

DAMM_SOURCE_COMMIT="bbfd605a1469cc83dac6e5f2650341c50ef69130"
DAMM_PUBLIC_REPOSITORY="https://github.com/World-Bank-Digital/DAMM"
DAMM_RENDERER_SHA256="95dcef014086f6c01f58678db426fb48d87546b8b6a4315c530801b1ff74c5be"
NETLIFY_RELEASE_IMAGE="node:22.22.3-bookworm@sha256:46e94f8cf91baab69a2deb3153e74eeffd73c20c7cc1d8432f5b96469eaa0322"
NETLIFY_FUNCTION_RUNTIME="nodejs22.x"

stop() {
  printf '\n  %s%sSTOP:%s %s\n\n' "$BOLD" "$RED" "$RESET" "$1" >&2
  exit 1
}

confirm_or_stop() {
  confirm "$1" || stop "${2:-The required confirmation was not given.}"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || stop "Required command '$1' is not installed."
}

require_value() {
  local name="$1" value="$2"
  [[ -n "${value//[[:space:]]/}" ]] || stop "$name cannot be blank."
}

require_sha256() {
  local name="$1" value="$2"
  [[ "$value" =~ ^[a-f0-9]{64}$ ]] || stop "$name must be a lowercase 64-character SHA-256."
}

require_email() {
  local name="$1" value="$2"
  [[ "$value" =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ ]] ||
    stop "$name must be a valid email address."
}

validate_neon_connection() {
  local variable_name="$1" mode="$2"
  printf '%s' "${!variable_name}" |
    node scripts/validate-neon-deployment-urls.mjs "$mode"
}

validate_same_neon_database() {
  local pooled_name="$1" direct_name="$2"
  printf '%s\0%s' "${!pooled_name}" "${!direct_name}" |
    node scripts/validate-neon-deployment-urls.mjs pair
}

attest_anonymous_damm_pin() {
  (
    set -eu
    local audit_root audit_home audit_repo
    audit_root=$(mktemp -d)
    trap 'rm -rf -- "$audit_root"' EXIT HUP INT TERM
    audit_home="$audit_root/home"
    audit_repo="$audit_root/repository"
    install -d -m 0700 "$audit_home" "$audit_home/.config" "$audit_repo"
    export HOME="$audit_home" XDG_CONFIG_HOME="$audit_home/.config"
    unset GIT_CONFIG_PARAMETERS GIT_CONFIG_COUNT
    export GIT_CONFIG_COUNT=0
    export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1
    export GIT_TERMINAL_PROMPT=0 GIT_ASKPASS=/bin/false
    git -C "$audit_repo" init --quiet
    git -C "$audit_repo" remote add origin "$DAMM_PUBLIC_REPOSITORY"
    git -C "$audit_repo" -c credential.helper= fetch --quiet --depth=1 --no-tags origin "$DAMM_SOURCE_COMMIT"
    git -C "$audit_repo" checkout --quiet --detach "$DAMM_SOURCE_COMMIT"
    [[ "$(git -C "$audit_repo" rev-parse HEAD)" == "$DAMM_SOURCE_COMMIT" ]]
    [[ "$(git -C "$audit_repo" rev-parse FETCH_HEAD)" == "$DAMM_SOURCE_COMMIT" ]]
    [[ "$(git -C "$audit_repo" rev-parse --is-shallow-repository)" == "true" ]]
    [[ "$(git -C "$audit_repo" rev-list --count --all)" == "1" ]]
    [[ -z "$(git -C "$audit_repo" tag --list)" ]]
    [[ -z "$(git -C "$audit_repo" status --porcelain=v1 --untracked-files=all)" ]]
    git -C "$audit_repo" fsck --strict --no-dangling >/dev/null
  )
}

verify_bound_release_sources() {
  (
    set -eu
    local local_sha tracking_sha remote_sha
    git fetch --quiet origin main
    local_sha=$(git rev-parse HEAD)
    tracking_sha=$(git rev-parse origin/main)
    remote_sha=$(git ls-remote origin refs/heads/main | awk 'NR == 1 { print $1 }')
    [[ "$local_sha" == "$DEPLOY_GIT_SHA" ]]
    [[ "$tracking_sha" == "$DEPLOY_GIT_SHA" ]]
    [[ "$remote_sha" == "$DEPLOY_GIT_SHA" ]]
    attest_anonymous_damm_pin
  )
}

remove_env() {
  local key="$1" tmp
  [[ -f "$ENV_FILE" ]] || return 0
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  mv "$tmp" "$ENV_FILE"
  printf '  %s✓ removed%s stale %s from %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

write_optional() {
  local key="$1" value="$2"
  if [[ -n "$value" ]]; then
    write_env "$key" "$value"
  else
    remove_env "$key"
  fi
}

generate_secret() {
  local key="$1" current
  current=$(_existing "$key" || true)
  if [[ -z "$current" ]]; then
    current=$(openssl rand -base64 48 | tr -d '\n')
  fi
  printf -v "$key" '%s' "$current"
  write_env "$key" "$current"
}

banner "DAR Studio · Ohio staging deployment"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Merged main and architectural stop checks"
say "Provision only from the merged main branch. The first checks avoid spending money on a topology that cannot meet the product contract."
require_command git
require_command node
require_command npm
require_command openssl
require_command docker

[[ -d .git && -f package.json ]] || stop "Run this wizard from the dar-studio-v2 repository root."
[[ "$(git branch --show-current)" == "main" ]] ||
  stop "Check out the merged main branch before provisioning."
[[ -z "$(git status --porcelain)" ]] ||
  stop "The worktree is not clean. Preserve or commit its changes before provisioning."

say "Refreshing the read-only view of origin/main…"
git fetch --quiet origin main || stop "Could not fetch origin/main. Check GitHub access and retry."
LOCAL_SHA=$(git rev-parse HEAD)
TRACKING_SHA=$(git rev-parse origin/main)
REMOTE_SHA=$(git ls-remote origin refs/heads/main | awk 'NR == 1 { print $1 }')
[[ "$LOCAL_SHA" == "$TRACKING_SHA" && "$LOCAL_SHA" == "$REMOTE_SHA" ]] ||
  stop "Local HEAD, origin/main, and the direct GitHub branch hash do not match."
DEPLOY_GIT_SHA="$LOCAL_SHA"
write_env DEPLOY_GIT_SHA "$DEPLOY_GIT_SHA"

required_files=(
  netlify.toml
  render.yaml
  Dockerfile.artifact-gateway
  Dockerfile.worker
  deploy/artifact-gateway/package.json
  deploy/artifact-gateway/package-lock.json
  deploy/worker/entrypoint.sh
  deploy/worker/preflight.mjs
  scripts/artifact-gateway.ts
  scripts/verify-build-no-secrets.mjs
  scripts/verify-netlify-function-bundle.mjs
  scripts/validate-neon-deployment-urls.mjs
  migrations/0013_damm_methodology_pin_cutover.sql
  migrations/0014_damm_source_pin_cutover.sql
  migrations/0015_damm_source_pin_cutover.sql
  migrations/0016_damm_source_pin_cutover.sql
  migrations/0017_damm_source_pin_cutover.sql
  migrations/0018_damm_source_pin_cutover.sql
  migrations/0019_progressive_stage_artifacts.sql
  migrations/0020_damm_source_pin_cutover.sql
  migrations/0021_damm_source_pin_cutover.sql
  migrations/0022_damm_source_pin_cutover.sql
  migrations/0023_damm_source_pin_cutover.sql
  migrations/0024_damm_source_pin_cutover.sql
  migrations/0025_damm_source_pin_cutover.sql
  migrations/0026_damm_source_pin_cutover.sql
  migrations/0027_damm_source_pin_cutover.sql
  migrations/0028_damm_source_pin_cutover.sql
  migrations/0029_damm_source_pin_cutover.sql
  migrations/0030_damm_source_pin_cutover.sql
  docs/DEPLOYMENT-NETLIFY-NEON-RENDER-OHIO.md
)
for required_file in "${required_files[@]}"; do
  [[ -f "$required_file" ]] || stop "Merged deployment file $required_file is missing."
done
grep -Fq "\"commit\": \"$DAMM_SOURCE_COMMIT\"" src/data/damm_model_manifest.json ||
  stop "The app manifest does not pin the authorized canonical DAMM merge."
grep -Fq "\"repository\": \"$DAMM_PUBLIC_REPOSITORY\"" src/data/damm_model_manifest.json ||
  stop "The app manifest does not pin the canonical public DAMM repository."
grep -Fq "\"sha256\": \"$DAMM_RENDERER_SHA256\"" src/data/damm_model_manifest.json ||
  stop "The app manifest does not pin the authorized DAMM renderer digest."
attest_anonymous_damm_pin ||
  stop "The manifest-pinned public DAMM commit is not anonymously fetchable without a credential."
grep -q "name: dar-studio-artifacts" render.yaml || stop "render.yaml does not declare the artifact gateway."
grep -q "healthCheckPath: /healthz" render.yaml || stop "render.yaml does not declare the artifact gateway health check."
[[ "$(grep -c "region: ohio" render.yaml)" -eq 2 ]] || stop "render.yaml does not pin both Render services to Ohio."
[[ "$(grep -c "plan: 1c-2g" render.yaml)" -eq 2 ]] || stop "render.yaml does not pin both Render services to plan 1c-2g."
[[ "$(grep -c "autoDeployTrigger: off" render.yaml)" -eq 2 ]] || stop "render.yaml must disable automatic deploys for both services."
[[ "$(grep -c "numInstances: 1" render.yaml)" -eq 2 ]] || stop "render.yaml must declare one instance of each service."
[[ "$(grep -c "maxShutdownDelaySeconds: 300" render.yaml)" -eq 1 ]] ||
  stop "Only the diskless artifact gateway may declare a 300-second shutdown delay."
grep -q "type: worker" render.yaml || stop "render.yaml does not declare a background worker."
grep -q "type: web" render.yaml || stop "render.yaml does not declare an artifact web service."
grep -q "dockerfilePath: ./Dockerfile.worker" render.yaml || stop "render.yaml does not pin the worker Dockerfile."
grep -q "dockerfilePath: ./Dockerfile.artifact-gateway" render.yaml || stop "render.yaml does not pin the gateway Dockerfile."
grep -q "name: dar-studio-worker-data" render.yaml || stop "render.yaml does not declare the worker disk."
grep -q "mountPath: /var/data" render.yaml || stop "render.yaml does not mount the worker disk at /var/data."
grep -q "sizeGB: 10" render.yaml || stop "render.yaml does not pin the worker disk to 10 GB."
for render_key in DATABASE_URL ARTIFACT_DELIVERY_SECRET APP_ORIGIN EXA_API_KEY JINA_API_KEY PERPLEXITY_API_KEY ANTHROPIC_API_KEY OPENAI_API_KEY GEMINI_API_KEY; do
  grep -q "key: $render_key" render.yaml || stop "render.yaml is missing required environment key $render_key."
done
[[ "$(grep -c "key: DATABASE_URL" render.yaml)" -eq 2 ]] || stop "Both Render services must receive their own pooled DATABASE_URL."
grep -Fq 'GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1 GIT_TERMINAL_PROMPT=0 GIT_ASKPASS=/bin/false git -C /opt/damm-seed fetch --depth=1 --no-tags origin "$commit"' Dockerfile.worker ||
  stop "Dockerfile.worker does not anonymously shallow-fetch only the pinned public DAMM commit."
if grep -Eiq '(type=secret|/root/\.netrc|DAMM_(GIT_)?(TOKEN|PAT|PASSWORD)|GITHUB_(TOKEN|PAT|PASSWORD)|GH_(TOKEN|PAT|PASSWORD))' Dockerfile.worker ||
   grep -Eiq 'key:[[:space:]]*(DAMM_(GIT_)?(TOKEN|PAT|PASSWORD)|GITHUB_(TOKEN|PAT|PASSWORD)|GH_(TOKEN|PAT|PASSWORD))' render.yaml; then
  stop "The public DAMM build must not accept a source credential through BuildKit, Docker, or Render."
fi
grep -q "MIGRATION_DATABASE_URL" scripts/migrate.mjs ||
  stop "The migrator does not separate the direct migration URL from pooled runtime DATABASE_URL."
grep -qi "advisory" scripts/migrate.mjs ||
  stop "The deploy migrator has no visible Postgres advisory-lock guard."
grep -Rq "refusing the ephemeral PGLite fallback" src/lib ||
  stop "Hosted execution is not visibly configured to fail closed without DATABASE_URL."
grep -Rq "VITE_GROK_AUTH_ENABLED" src/lib src/routes scripts ||
  stop "The deployed social-auth gate is missing."
grep -q "ARTIFACT_DELIVERY_ENDPOINT_PATH" src/lib/damm-v17/artifact-delivery.ts ||
  stop "The Netlify artifact grant does not use the fixed gateway endpoint contract."
grep -q "ARTIFACT_DELIVERY_ENDPOINT_PATH" scripts/artifact-gateway.ts ||
  stop "The Render gateway does not use the fixed artifact endpoint contract."

confirm_or_stop "Run the complete local validation suite now?" \
  "A deployment must not proceed without repository validation."
npm test
npm run typecheck
npm run lint
npm run build:dev
npm run verify:netlify
for simulation_profile in minimal typical dense; do
  node scripts/simulate-workflow.mjs --scenario eight-stage-happy-v1 --profile "$simulation_profile"
  node scripts/simulate-workflow.mjs --scenario nigeria-stage6-overlength-v1 --profile "$simulation_profile"
done
node scripts/simulate-workflow.mjs --scenario nigeria-stage6-through-package-v1 --profile typical
say "Local validation passed at $DEPLOY_GIT_SHA."
pause "Continue to infrastructure account and release authorization?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Infrastructure access and release authorization"
say "Both Render 1c-2g services and the worker's persistent disk are billed. This stage does not authorize provider inference/search or the separately gated paid canary."
open_url "https://app.netlify.com/"
open_url "https://console.neon.tech/app/projects"
open_url "https://dashboard.render.com/"
step "Confirm you can administer all three accounts, view usage, and rotate their credentials."
step "Confirm GitHub access to World-Bank-Digital/dar-studio-v2 and anonymous read access to the public DAMM repository. The worker build must not receive a GitHub source credential or token."
confirm_or_stop \
  "Are you authorized to create the Neon project, both paid Render services, the worker disk, administer release credentials, migrate, and deploy?" \
  "Cost authority is required before any cloud resource is created."
write_env DEPLOYMENT_ENVIRONMENT "staging"
pause "Infrastructure access and release authority are recorded?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Worker vendor credentials"
say "The country must remain the only required launch input, so all platform vendor keys must exist before the worker starts. Input is hidden and the local file is mode 0600."
open_url "https://dashboard.exa.ai/api-keys"
ask_secret EXA_API_KEY "Paste the Exa API key:"
require_value EXA_API_KEY "$EXA_API_KEY"
write_env EXA_API_KEY "$EXA_API_KEY"

open_url "https://jina.ai/api-dashboard/key-manager"
ask_secret JINA_API_KEY "Paste the Jina API key:"
require_value JINA_API_KEY "$JINA_API_KEY"
write_env JINA_API_KEY "$JINA_API_KEY"

open_url "https://www.perplexity.ai/settings/api"
ask_secret PERPLEXITY_API_KEY "Paste the Perplexity API key:"
require_value PERPLEXITY_API_KEY "$PERPLEXITY_API_KEY"
write_env PERPLEXITY_API_KEY "$PERPLEXITY_API_KEY"

open_url "https://console.anthropic.com/settings/keys"
ask_secret ANTHROPIC_API_KEY "Paste the Anthropic API key:"
require_value ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"

open_url "https://platform.openai.com/api-keys"
ask_secret OPENAI_API_KEY "Paste the OpenAI API key:"
require_value OPENAI_API_KEY "$OPENAI_API_KEY"
write_env OPENAI_API_KEY "$OPENAI_API_KEY"

open_url "https://aistudio.google.com/app/apikey"
ask_secret GEMINI_API_KEY "Paste the Gemini API key:"
require_value GEMINI_API_KEY "$GEMINI_API_KEY"
write_env GEMINI_API_KEY "$GEMINI_API_KEY"
chmod 600 "$ENV_FILE"
step "Do not commit, print, or import this whole file into either cloud dashboard. Each platform receives only its own keys."
pause "All six worker credentials are present?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Neon project in AWS Ohio"
open_url "https://console.neon.tech/app/projects"
step "Click New Project. Name it dar-studio-staging (or another staging-only name)."
step "Choose AWS and US East (Ohio), region ID aws-us-east-2. Do not accept the current N. Virginia default."
step "Create the project, then select its root production branch. Do not use the child development branch."
ask NEON_PROJECT_NAME "Neon project name:"
require_value NEON_PROJECT_NAME "$NEON_PROJECT_NAME"
ask NEON_PROJECT_ID "Neon project ID:"
require_value NEON_PROJECT_ID "$NEON_PROJECT_ID"
ask NEON_BRANCH_ID "Neon production branch ID:"
require_value NEON_BRANCH_ID "$NEON_BRANCH_ID"
ask NEON_DATABASE_NAME "Neon database name (normally neondb):"
require_value NEON_DATABASE_NAME "$NEON_DATABASE_NAME"
ask NEON_ROLE_NAME "Neon database role used by both connection strings:"
require_value NEON_ROLE_NAME "$NEON_ROLE_NAME"
NEON_REGION="aws-us-east-2"
NEON_BRANCH="production"
write_env NEON_PROJECT_NAME "$NEON_PROJECT_NAME"
write_env NEON_PROJECT_ID "$NEON_PROJECT_ID"
write_env NEON_REGION "$NEON_REGION"
write_env NEON_BRANCH "$NEON_BRANCH"
write_env NEON_BRANCH_ID "$NEON_BRANCH_ID"
write_env NEON_DATABASE_NAME "$NEON_DATABASE_NAME"
write_env NEON_ROLE_NAME "$NEON_ROLE_NAME"
confirm_or_stop "Does Neon show AWS US East (Ohio) / aws-us-east-2 and a parentless production branch?" \
  "The Neon region and root branch are immutable safety choices for this deployment."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Pooled runtime and direct migration URLs"
say "In the Neon project Dashboard click Connect. Select production and the intended database/role."
step "Turn Connection pooling on. Copy the URL whose hostname contains -pooler."
ask_secret DATABASE_URL "Paste the pooled Neon DATABASE_URL:"
require_value DATABASE_URL "$DATABASE_URL"
validate_neon_connection DATABASE_URL pooled ||
  stop "DATABASE_URL must be Neon's pooled Ohio URL with sslmode=require."
write_env DATABASE_URL "$DATABASE_URL"

step "Turn Connection pooling off and copy the direct URL."
ask_secret DATABASE_URL_DIRECT "Paste the direct Neon migration URL:"
require_value DATABASE_URL_DIRECT "$DATABASE_URL_DIRECT"
validate_neon_connection DATABASE_URL_DIRECT direct ||
  stop "DATABASE_URL_DIRECT must be Neon's direct Ohio URL with sslmode=require."
validate_same_neon_database DATABASE_URL DATABASE_URL_DIRECT ||
  stop "Pooled and direct URLs must identify the same Neon endpoint, database, and role."
write_env DATABASE_URL_DIRECT "$DATABASE_URL_DIRECT"
chmod 600 "$ENV_FILE"
say "Pooled: Netlify Build+Functions and both Render services. Direct: local migration and Netlify Build-only MIGRATION_DATABASE_URL."
pause "Both URLs were copied from the same production branch, database, and role?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Migration preflight and recovery snapshot"
open_url "https://console.neon.tech/app/projects/$NEON_PROJECT_ID"
step "Open SQL Editor; select production and the intended database."
say "Run: select to_regclass('public.runs') as runs_table;"
say "If it is non-null, run the active-workflow query in docs/DEPLOYMENT-NETLIFY-NEON-RENDER-OHIO.md."
confirm_or_stop "Did the active-workflow query return zero rows?" \
  "Do not migrate while any workflow is queued, running, or otherwise nonterminal."
step "Open Backup & Restore, enable Enhanced view if shown, select the root production branch, and click Create snapshot."
step "Name it with UTC time and the deploy commit, for example pre-0030-YYYYMMDD-HHMM-${DEPLOY_GIT_SHA:0:8}."
ask NEON_SNAPSHOT_NAME "Exact pre-migration snapshot name:"
require_value NEON_SNAPSHOT_NAME "$NEON_SNAPSHOT_NAME"
write_env NEON_SNAPSHOT_NAME "$NEON_SNAPSHOT_NAME"
confirm_or_stop "Is that snapshot complete, non-expiring, and visibly tied to the root production branch?" \
  "A recoverable snapshot is required before migration."
warn "Existing deployment only: suspend the preceding-pin Render worker before applying 0030. A reviewed merge is inert only while Netlify builds and Deploy Previews are disabled, Render service auto-deploys are off, and any Blueprint is disconnected. Leave the worker suspended until the exact repinned image is Live; queued arrivals must remain unclaimed and unspent meanwhile."
confirm_or_stop "Is there no preceding-pin worker because this is a new environment, or is the existing worker visibly suspended?" \
  "Do not migrate while a preceding-pin worker can claim newly pinned runs."
step "For an existing site, freshly re-read Netlify Project configuration > Build & deploy after the worker suspension gate and require builds stopped and Deploy Previews disabled. For a new environment, require that no Netlify site exists yet."
confirm_or_stop "Are Netlify builds still stopped and Deploy Previews still disabled, or does no Netlify site exist yet?" \
  "Do not migrate while a Git update could create an unreviewed Netlify build or preview."
step "Freshly open both existing Render services and require automatic deploys and PR previews to remain off. If this is a new environment, confirm that neither service exists yet."
confirm_or_stop "Do both existing Render services still have automatic deploys off, or are both services not yet created?" \
  "Do not migrate while either Render service can deploy automatically."
step "Freshly inspect the Render Blueprint list. Require the provisioning Blueprint to remain disconnected or absent; do not reconnect it for this check."
confirm_or_stop "Is the provisioning Blueprint still disconnected or absent?" \
  "Do not migrate while a Blueprint can synchronize the repository into managed services."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Apply and verify migration 0030 after 0019 through 0029"
warn "This preserves the sealed progressive Stage 1-7 schema and prior source cutovers before repinning the worker to the reviewed DAMM revision with corrected Exa document-ID validation and safe private diagnostics; exact status/URL binding, source pricing, conservative settlement, and durable paid-request replay protection remain unchanged. The direct URL is used, and the migrator takes its Postgres advisory lock."
confirm_or_stop "Run the idempotent migration set against this Neon staging database now?" \
  "Migration was not authorized. No worker may be deployed yet."
DATABASE_URL="$DATABASE_URL" MIGRATION_DATABASE_URL="$DATABASE_URL_DIRECT" npm run db:migrate ||
  stop "Migration failed. Keep the snapshot, read the exact error, and do not deploy the worker."
open_url "https://console.neon.tech/app/projects/$NEON_PROJECT_ID"
step "In SQL Editor, query _migrations for 0019_progressive_stage_artifacts.sql and 0020 through 0030 DAMM source-pin cutovers. Require exactly one row for each, in that order."
step "Require both progressive-publication tables and their sealing triggers, then run the function checks in the guide. Require pinned_commit=true, renderer_digest=true, and remains_unratified=true."
step "Require exactly 30 total migration rows through 0030, repeat the zero-active-workflow query, and run the guide's preserved-failure query. Require all eight protected failed run IDs (7e301235, e96a93fd, b481ddea, fcc17f6c, 9e5e8a13, 615e7139, b0c325f0, 27e2515e), stage counts, spend, publication/artifact counts, null final set, and null claim to remain unchanged."
confirm_or_stop "Did every 0019 through 0030 migration verification query return the exact expected result?" \
  "A worker cannot start on an unverified schema or methodology pin."
write_env MIGRATION_0019_VERIFIED "true"
write_env MIGRATION_0020_VERIFIED "true"
write_env MIGRATION_0021_VERIFIED "true"
write_env MIGRATION_0022_VERIFIED "true"
write_env MIGRATION_0023_VERIFIED "true"
write_env MIGRATION_0024_VERIFIED "true"
write_env MIGRATION_0025_VERIFIED "true"
write_env MIGRATION_0026_VERIFIED "true"
write_env MIGRATION_0027_VERIFIED "true"
write_env MIGRATION_0028_VERIFIED "true"
write_env MIGRATION_0029_VERIFIED "true"
write_env MIGRATION_0030_VERIFIED "true"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Import or verify the main branch in Netlify, then freeze builds"
open_url "https://app.netlify.com/"
step "For a new site: Team Projects > Add new project > Import an existing project > GitHub. For this existing site, verify it remains linked to the exact repository instead of importing a duplicate."
step "Require the exact World-Bank-Digital/dar-studio-v2 repository and production branch main. Keep netlify.toml's build and publish settings."
step "For a new site, choose the staging slug. A first build before environment setup must fail closed; do not accept a usable empty/PGLite app."
ask NETLIFY_PROJECT_SLUG "Netlify project slug (without .netlify.app):"
require_value NETLIFY_PROJECT_SLUG "$NETLIFY_PROJECT_SLUG"
[[ "$NETLIFY_PROJECT_SLUG" =~ ^[a-z0-9][a-z0-9-]*[a-z0-9]$ ]] ||
  stop "The Netlify slug must contain lowercase letters, digits, and hyphens."
NETLIFY_URL="https://${NETLIFY_PROJECT_SLUG}.netlify.app"
VITE_PUBLIC_HOSTNAME="${NETLIFY_PROJECT_SLUG}.netlify.app"
BETTER_AUTH_URL="$NETLIFY_URL"
ask NETLIFY_SITE_ID "Project configuration > General > Project information > Site ID:"
require_value NETLIFY_SITE_ID "$NETLIFY_SITE_ID"
write_env NETLIFY_PROJECT_SLUG "$NETLIFY_PROJECT_SLUG"
write_env NETLIFY_SITE_ID "$NETLIFY_SITE_ID"
write_env NETLIFY_URL "$NETLIFY_URL"
write_env VITE_PUBLIC_HOSTNAME "$VITE_PUBLIC_HOSTNAME"
write_env BETTER_AUTH_URL "$BETTER_AUTH_URL"
open_url "https://app.netlify.com/sites/$NETLIFY_PROJECT_SLUG/deploys"
step "Wait until the expected initial deploy reaches a terminal state, canceling it first if necessary; do not inspect it as acceptance evidence."
step "Immediately stop Netlify builds under Project configuration > Build & deploy > Continuous deployment > Build settings."
step "After Save and a full reload or API read, require stop_builds=true. Build hooks, UI/API Git builds, branch deploys, and previews must now be inert."
ask NETLIFY_BASELINE_DEPLOY_ID "Latest deploy ID for the frozen deploy-history baseline:"
require_value NETLIFY_BASELINE_DEPLOY_ID "$NETLIFY_BASELINE_DEPLOY_ID"
ask NETLIFY_BASELINE_DEPLOY_SHA "Commit SHA shown for that baseline deploy, or 'none' for a commitless failed import:"
require_value NETLIFY_BASELINE_DEPLOY_SHA "$NETLIFY_BASELINE_DEPLOY_SHA"
write_env NETLIFY_BASELINE_DEPLOY_ID "$NETLIFY_BASELINE_DEPLOY_ID"
write_env NETLIFY_BASELINE_DEPLOY_SHA "$NETLIFY_BASELINE_DEPLOY_SHA"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Netlify Ohio, deploy isolation, and private access"
open_url "https://app.netlify.com/sites/$NETLIFY_PROJECT_SLUG/configuration/deploys"
step "Project configuration > Build & deploy > Continuous deployment > Functions region: confirm cmh / US East (Ohio)."
step "Branches and deploy contexts > Configure: production branch main, Branch deploys None, Deploy Previews disabled."
step "Project configuration > General > Visitor access > Password Protection: prefer Team protection. If Team protection is plan-gated, Basic protection is acceptable only with separate credential authority and an approved storage, distribution, and rotation plan. No protection settings is forbidden. Store any Basic password only in the operator's password manager or Keychain, never this env file."
confirm_or_stop "Are Functions in cmh Ohio, branch deploys off, Deploy Previews off, and Visitor access actually protected?" \
  "Region, database isolation, and spend protection must be fixed before secrets are added."
remove_env NETLIFY_VISITOR_ACCESS_MODE
ask NETLIFY_VISITOR_ACCESS_MODE "Persisted Visitor access mode (team or basic):"
case "$NETLIFY_VISITOR_ACCESS_MODE" in
  team) NETLIFY_VISITOR_ACCESS_LABEL="Team protection" ;;
  basic)
    NETLIFY_VISITOR_ACCESS_LABEL="Basic protection"
    confirm_or_stop "Was Basic protection explicitly authorized, with its password confined to an approved password manager or Keychain and a defined distribution/rotation plan?" \
      "Basic protection needs separate credential authority; otherwise choose Team protection or stop."
    ;;
  *) stop "Visitor access mode must be exactly team or basic." ;;
esac
confirm_or_stop "After Save and a fresh configuration reload, does Netlify show Protected by $NETLIFY_VISITOR_ACCESS_LABEL and Access restricted to All deploys?" \
  "A click or a local private record does not prove that the live access setting persisted."
confirm_or_stop "Does an anonymous request receive the protection boundary rather than the application HTML?" \
  "Do not start the paid worker behind a publicly reachable launch surface."
confirm_or_stop "Can a fresh authorized session complete the protection challenge and reach DAR Studio?" \
  "Private access must deny anonymous visitors without locking out intended operators."
write_env NETLIFY_FUNCTION_REGION "cmh"
write_env NETLIFY_DEPLOY_PREVIEWS "disabled"
write_env NETLIFY_PROJECT_VISIBILITY "private"
write_env NETLIFY_VISITOR_ACCESS_MODE "$NETLIFY_VISITOR_ACCESS_MODE"
write_env NETLIFY_VISITOR_ACCESS_SCOPE "all-deploys"
write_env NETLIFY_ANONYMOUS_DENIAL_VERIFIED "true"
write_env NETLIFY_AUTHORIZED_ACCESS_VERIFIED "true"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Stable auth secrets and exact callback mode"
generate_secret DAR_KEY_SECRET
generate_secret BETTER_AUTH_SECRET
generate_secret ARTIFACT_DELIVERY_SECRET
write_env VITE_AUTH_ENABLED "true"

say "Choose 'email' for email/password, or 'broker' for Google/X through a dedicated Grok broker client."
ask AUTH_MODE "Authentication mode (email or broker):"
case "$AUTH_MODE" in
  email)
    VITE_GROK_AUTH_ENABLED="false"
    remove_env GROK_AUTH_ISSUER
    remove_env GROK_AUTH_CLIENT_ID
    remove_env GROK_AUTH_CLIENT_SECRET
    remove_env GROK_GOOGLE_CALLBACK_URL
    remove_env GROK_X_CALLBACK_URL
    say "The Netlify login page must hide Google and X in this mode."
    ;;
  broker)
    VITE_GROK_AUTH_ENABLED="true"
    GROK_GOOGLE_CALLBACK_URL="$NETLIFY_URL/api/auth/oauth2/callback/grok-google"
    GROK_X_CALLBACK_URL="$NETLIFY_URL/api/auth/oauth2/callback/grok-x"
    say "Register exactly these callbacks with the broker operator:"
    say "$GROK_GOOGLE_CALLBACK_URL"
    say "$GROK_X_CALLBACK_URL"
    ask GROK_AUTH_ISSUER "Broker issuer (normally https://auth.grok.me):"
    require_value GROK_AUTH_ISSUER "$GROK_AUTH_ISSUER"
    [[ "$GROK_AUTH_ISSUER" == https://* ]] || stop "The broker issuer must be HTTPS."
    ask GROK_AUTH_CLIENT_ID "Dedicated Netlify app broker client ID:"
    require_value GROK_AUTH_CLIENT_ID "$GROK_AUTH_CLIENT_ID"
    ask_secret GROK_AUTH_CLIENT_SECRET "Dedicated Netlify app broker client secret:"
    require_value GROK_AUTH_CLIENT_SECRET "$GROK_AUTH_CLIENT_SECRET"
    write_env GROK_GOOGLE_CALLBACK_URL "$GROK_GOOGLE_CALLBACK_URL"
    write_env GROK_X_CALLBACK_URL "$GROK_X_CALLBACK_URL"
    write_env GROK_AUTH_ISSUER "$GROK_AUTH_ISSUER"
    write_env GROK_AUTH_CLIENT_ID "$GROK_AUTH_CLIENT_ID"
    write_env GROK_AUTH_CLIENT_SECRET "$GROK_AUTH_CLIENT_SECRET"
    ;;
  *) stop "AUTH_MODE must be exactly 'email' or 'broker'." ;;
esac
write_env AUTH_MODE "$AUTH_MODE"
write_env VITE_GROK_AUTH_ENABLED "$VITE_GROK_AUTH_ENABLED"

ask DAR_ADMIN_EMAILS "Optional comma-separated team-key admin emails (blank for none):"
write_optional DAR_ADMIN_EMAILS "$DAR_ADMIN_EMAILS"
if confirm "Configure Resend mail delivery now?"; then
  ask_secret RESEND_API_KEY "Resend API key:"
  require_value RESEND_API_KEY "$RESEND_API_KEY"
  ask EMAIL_FROM "Verified From address:"
  require_value EMAIL_FROM "$EMAIL_FROM"
  write_env RESEND_API_KEY "$RESEND_API_KEY"
  write_env EMAIL_FROM "$EMAIL_FROM"
else
  remove_env RESEND_API_KEY
  remove_env EMAIL_FROM
fi
if confirm "Configure the optional Netlify xAI platform key now?"; then
  ask_secret XAI_API_KEY "xAI API key:"
  require_value XAI_API_KEY "$XAI_API_KEY"
  write_env XAI_API_KEY "$XAI_API_KEY"
else
  remove_env XAI_API_KEY
fi
chmod 600 "$ENV_FILE"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Render Ohio Blueprint: worker and artifact gateway"
open_url "https://dashboard.render.com/"
say "Migrations 0019 through 0030 must already be verified. Render does not run database migrations."
step "Review dar-studio-worker: worker/docker, region ohio, plan 1c-2g, auto deploy off, one instance, and no max shutdown delay field."
step "Review disk dar-studio-worker-data at /var/data, 10 GB. Render forbids a custom max shutdown delay on a disk-backed service, so its documented 30-second default applies; checkpoints and the claim lease provide automatic recovery."
step "Review dar-studio-artifacts: web/docker, region ohio, plan 1c-2g, auto deploy off, one instance, health /healthz, max shutdown delay 300 seconds, no disk."
if confirm "Is this a new Render environment with no existing worker or gateway?"; then
  RENDER_ENVIRONMENT_MODE="new"
  RENDER_WORKER_NEEDS_RESUME="false"
  step "New environment only: New > Blueprint > Connect World-Bank-Digital/dar-studio-v2; select branch main and path render.yaml."
  step "At the initial worker sync:false prompts enter pooled DATABASE_URL and EXA, JINA, PERPLEXITY, ANTHROPIC, OPENAI, and GEMINI keys."
  step "For dar-studio-artifacts enter the same pooled DATABASE_URL, the generated ARTIFACT_DELIVERY_SECRET, and APP_ORIGIN=$NETLIFY_URL. Render supplies PORT; do not add it."
  step "Do not enter MIGRATION_DATABASE_URL, DAR_KEY_SECRET, BETTER_AUTH_SECRET, broker values, or any other Netlify-only value."
  warn "Render prompts for sync:false values only during initial Blueprint creation. Verify every runtime key before deployment. The public DAMM build uses no GitHub credential."
  confirm_or_stop "Does the review exactly match both Ohio services, the one worker disk, main commit, and each service's required secrets?" \
    "Do not create mismatched or incompletely configured paid services."
  confirm_or_stop "Does the active-workflow query still return zero rows before the initial Blueprint deploy?" \
    "Do not create a worker while any workflow is nonterminal."
  say "Refresh both bound source identities immediately before the initial Blueprint deploy."
  verify_bound_release_sources ||
    stop "A bound DAR or public DAMM source identity moved or became unreachable. Do not click Deploy Blueprint; restart from a reviewed source state."
  confirm_or_stop "Deploy this billed Blueprint now?" \
    "The paid Render mutation was not authorized."
  step "Click Deploy Blueprint once. The worker fetches the public DAMM source anonymously; do not start an overlapping manual deploy."
  step "Immediately open the new Blueprint's Settings page and set Auto Sync to No. Service auto-deploy is already off in render.yaml."
  confirm_or_stop "Are Blueprint Auto Sync and both services' automatic deploy triggers off while the initial builds settle?" \
    "Do not leave source automation enabled during the initial build."
  step "Wait for both initial credential-free deploys to reach terminal states—Live, Failed, or Canceled—without starting a second build."
  confirm_or_stop "Are both initial credential-free deploys Live on exactly $DEPLOY_GIT_SHA with zero active workflows?" \
    "Do not accept or retry an automatic, failed, canceled, wrong-commit, credential-bearing, or active-workflow initial deployment."
else
  RENDER_ENVIRONMENT_MODE="existing"
  RENDER_WORKER_NEEDS_RESUME="true"
  step "Existing deployment: keep an already-disconnected Blueprint disconnected and open the exact worker and gateway services directly."
  step "Existing deployment path: do not create or deploy a Blueprint. Re-read both service configurations, their required runtime secrets, the worker disk, and the frozen automatic-deploy settings directly."
  confirm_or_stop "Is the existing worker visibly Suspended, is the Blueprint absent, and do both services exactly match the reviewed Ohio configuration with automatic deploys off?" \
    "Do not change or deploy an existing service until its identity, configuration, automation freeze, and worker suspension are reverified."
  say "Refresh both bound source identities before the existing gateway deploy."
  verify_bound_release_sources ||
    stop "A bound DAR or public DAMM source identity moved or became unreachable. Keep the worker suspended and restart from a reviewed source state."
  step "With the existing worker still visibly Suspended, manually deploy the exact gateway commit first while the worker remains suspended. Require the gateway deploy to settle Live on $DEPLOY_GIT_SHA without changing its configuration."
  confirm_or_stop "Is the existing gateway Live on exactly $DEPLOY_GIT_SHA while the worker remains visibly Suspended?" \
    "Do not resume the worker until the gateway identity is exact and the worker remains unable to claim work."
fi
if [[ "$RENDER_WORKER_NEEDS_RESUME" == "true" ]]; then
  step "Require dar-studio-worker to be visibly Suspended. A Failed or idle service is not equivalent. Remove the legacy damm_git_netrc Secret File with Save only; verify that no deploy starts and the worker remains Suspended."
  confirm_or_stop "Is the service still visibly Suspended with damm_git_netrc absent and no GitHub source credential configured?" \
    "Do not resume a worker that can receive an unnecessary source credential."
  confirm_or_stop "Does the active-workflow query still return zero rows?" \
    "Zero-active gate failed: keep the worker suspended. Do not resume while any workflow is nonterminal."
  say "Refresh origin/main again immediately before resume."
  verify_bound_release_sources ||
    stop "Pre-resume source check failed: a bound DAR or public DAMM identity moved or became unreachable; keep the worker suspended and restart from a reviewed source state."
  confirm_or_stop "Does Render's displayed latest commit to build equal $DEPLOY_GIT_SHA?" \
    "Keep the worker suspended; never resume a different commit."
  step "Resume the suspended worker. Render starts the exact latest-commit build; do not start an overlapping manual deploy. Require the public DAMM fetch to be anonymous, with no build credential or token configured."
  step "Wait until that deploy reaches a terminal state—Live, Failed, or Canceled—before inspecting or retrying any failure."
  step "Verify the settled deploy is Live on commit $DEPLOY_GIT_SHA. Every retry requires revalidating origin/main, suspending the worker, reconfirming zero active workflows, and repeating the immediate pre-resume source/Render target checks."
  confirm_or_stop "Is the credential-free worker deploy Live on the exact recorded commit?" \
    "Do not continue to runtime verification from a failed, canceled, wrong-commit, or credential-bearing deploy."
else
  confirm_or_stop "Is the initial credential-free worker deploy still Live on exactly $DEPLOY_GIT_SHA, with zero active workflows and no GitHub source credential configured?" \
    "Do not continue from a wrong-commit, credential-bearing, or active-workflow initial deploy."
fi
ask RENDER_WORKER_SERVICE_ID "dar-studio-worker service ID from its Settings page or URL:"
require_value RENDER_WORKER_SERVICE_ID "$RENDER_WORKER_SERVICE_ID"
ask RENDER_ARTIFACT_SERVICE_ID "dar-studio-artifacts service ID from its Settings page or URL:"
require_value RENDER_ARTIFACT_SERVICE_ID "$RENDER_ARTIFACT_SERVICE_ID"
ask ARTIFACT_GATEWAY_URL "dar-studio-artifacts public HTTPS origin (no trailing slash):"
require_value ARTIFACT_GATEWAY_URL "$ARTIFACT_GATEWAY_URL"
[[ "$ARTIFACT_GATEWAY_URL" =~ ^https://[a-z0-9]([a-z0-9-]*[a-z0-9])?\.onrender\.com$ ]] ||
  stop "ARTIFACT_GATEWAY_URL must be the exact Render HTTPS origin with no path or trailing slash."
write_env RENDER_WORKER_SERVICE_ID "$RENDER_WORKER_SERVICE_ID"
write_env RENDER_ARTIFACT_SERVICE_ID "$RENDER_ARTIFACT_SERVICE_ID"
write_env ARTIFACT_GATEWAY_URL "$ARTIFACT_GATEWAY_URL"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Render worker and artifact gateway verification"
open_url "https://dashboard.render.com/worker/$RENDER_WORKER_SERVICE_ID"
step "Open worker Logs. Require [worker-checkout] installed/reusing, [worker-preflight] ready, and [worker] host/pipeline/interpreter/watching queue lines."
step "Require DAMM commit $DAMM_SOURCE_COMMIT, clean source, /var/data/checkouts/$DAMM_SOURCE_COMMIT, and /opt/damm-venv/bin/python."
step "Require renderer SHA-256 $DAMM_RENDERER_SHA256, node=22.22.3, python=3.12.13, migrations=30 through 0030, Pandoc, LibreOffice/soffice, six nonempty vendor variables with pinned SDK imports, blank mode-0600 upstream .env, and queue watching."
warn "Any worker-checkout, worker-preflight, or worker-entrypoint failed line, checkout drift, missing renderer/vendor, or crash loop is a hard stop."
ask RENDER_WORKER_DEPLOY_ID "Successful Render worker deploy ID:"
require_value RENDER_WORKER_DEPLOY_ID "$RENDER_WORKER_DEPLOY_ID"
ask RENDER_WORKER_DEPLOY_SHA "Commit SHA shown for the worker deploy:"
[[ "$RENDER_WORKER_DEPLOY_SHA" == "$DEPLOY_GIT_SHA" ]] ||
  stop "The Render worker did not deploy the recorded origin/main commit."
write_env RENDER_WORKER_DEPLOY_ID "$RENDER_WORKER_DEPLOY_ID"
write_env RENDER_WORKER_DEPLOY_SHA "$RENDER_WORKER_DEPLOY_SHA"
open_url "$ARTIFACT_GATEWAY_URL/healthz"
step "Require gateway status 200, body {\"status\":\"ok\"}, and Cache-Control: no-store."
step "Request fixed $ARTIFACT_GATEWAY_URL/v1/artifacts without the exact Origin and Authorization header; require a non-disclosing 404 with body Not found."
open_url "https://dashboard.render.com/web/$RENDER_ARTIFACT_SERVICE_ID"
step "Open gateway Logs; require [artifact-gateway] listening on 0.0.0.0:<PORT> and no secret or database URL."
ask RENDER_ARTIFACT_DEPLOY_ID "Successful Render artifact gateway deploy ID:"
require_value RENDER_ARTIFACT_DEPLOY_ID "$RENDER_ARTIFACT_DEPLOY_ID"
ask RENDER_ARTIFACT_DEPLOY_SHA "Commit SHA shown for the artifact gateway deploy:"
[[ "$RENDER_ARTIFACT_DEPLOY_SHA" == "$DEPLOY_GIT_SHA" ]] ||
  stop "The Render artifact gateway did not deploy the recorded origin/main commit."
write_env RENDER_ARTIFACT_DEPLOY_ID "$RENDER_ARTIFACT_DEPLOY_ID"
write_env RENDER_ARTIFACT_DEPLOY_SHA "$RENDER_ARTIFACT_DEPLOY_SHA"
confirm_or_stop "Are both services stable, on the exact commit, and free of preflight, health, or disclosure failures?" \
  "Do not expose Netlify or launch a workflow while either Render service is unverified."
if [[ "$RENDER_ENVIRONMENT_MODE" == "new" ]]; then
  step "Only now inspect the newly created Blueprint, open its Settings page, and choose Disconnect Blueprint. Require the confirmation to say: Resources will no longer sync automatically from your Blueprint file. This will not delete the file itself. This will not delete the managed resources. You can always connect your file later from the Blueprint page."
  confirm_or_stop "Does the disconnection confirmation explicitly preserve the managed worker and gateway without a deploy or billing action?" \
    "Do not disconnect if the warning differs, deletes a managed resource, triggers a deploy, or has any billing effect."
  step "Confirm Disconnect Blueprint, then require the Blueprint to disappear and its Sync Hook to be unavailable. Do not request the old Sync Hook URL with any HTTP method because a probe could trigger a sync."
else
  step "If the Blueprint is already absent, do not reconnect it. Re-open the Blueprint list and require it to remain absent; do not create, deploy, synchronize, or disconnect anything."
fi
confirm_or_stop "Is the Blueprint already disconnected, or was disconnected only after the safe preservation confirmation?" \
  "Do not continue unless the Blueprint is absent and no disconnection changed a managed resource, triggered a deploy, or had any billing effect."
step "Re-read both services after disconnection. Require that the worker and gateway remain Live on their unchanged deploy IDs and commits, both retain Auto-Deploy and PR Previews Off, and the worker disk remains attached at /var/data with its recorded size."
confirm_or_stop "Is the Blueprint disconnected while both managed services and the worker disk remain unchanged?" \
  "Do not record a safe terminal state until the services, deploy identities, automation freezes, and disk are independently reverified."
remove_env RENDER_BLUEPRINT_ID
remove_env RENDER_BLUEPRINT_AUTO_SYNC
write_env RENDER_BLUEPRINT_STATE "disconnected"

# ── 13 ────────────────────────────────────────────────────────────────────
stage "Netlify production-only environment"
open_url "https://app.netlify.com/sites/$NETLIFY_PROJECT_SLUG/configuration/env"
warn "Do not import the whole $ENV_FILE file: it contains Render-only keys and values with different Netlify scopes."
step "Add AWS_LAMBDA_JS_RUNTIME=$NETLIFY_FUNCTION_RUNTIME: all deploy contexts, Functions only, non-secret. This deliberate cross-context exception is required because pinned CLI no-build packaging reads the dev Functions envelope."
step "Add pooled DATABASE_URL: Production context, Builds + Functions scopes, secret."
step "Add MIGRATION_DATABASE_URL from local DATABASE_URL_DIRECT: Production context, Builds scope only, secret."
step "Add EXPECTED_DEPLOY_GIT_SHA=$DEPLOY_GIT_SHA: Production context, Builds scope only, non-secret."
step "Add DAR_KEY_SECRET, BETTER_AUTH_SECRET, and BETTER_AUTH_URL: Production, Builds + Functions. Mark both secrets."
step "Add ARTIFACT_GATEWAY_URL=$ARTIFACT_GATEWAY_URL and ARTIFACT_DELIVERY_SECRET: Production, Builds + Functions. Mark the secret."
step "Add VITE_AUTH_ENABLED=true and VITE_GROK_AUTH_ENABLED=$VITE_GROK_AUTH_ENABLED: Production, Builds + Functions."
step "Add VITE_PUBLIC_HOSTNAME=$VITE_PUBLIC_HOSTNAME: Production, Builds only."
if [[ "$AUTH_MODE" == "broker" ]]; then
  step "Add GROK_AUTH_ISSUER, GROK_AUTH_CLIENT_ID, and GROK_AUTH_CLIENT_SECRET: Production, Builds + Functions; mark the secret."
fi
[[ -n "$DAR_ADMIN_EMAILS" ]] && step "Add DAR_ADMIN_EMAILS: Production, Functions only."
[[ -n "${RESEND_API_KEY:-}" ]] && step "Add RESEND_API_KEY (secret) and EMAIL_FROM: Production, Functions only."
[[ -n "${XAI_API_KEY:-}" ]] && step "Add XAI_API_KEY: Production, Functions only, secret."
step "Confirm no database URL, auth secret, encryption key, broker value, artifact secret, mail key, or AI key has any Preview/branch/dev context."
confirm_or_stop "Does the Netlify environment list exactly match these keys, contexts, and scopes?" \
  "Incorrect scopes can leak staging data or make the build preflight silently invalid."
write_env NETLIFY_ENVIRONMENT_VERIFIED "true"

# ── 14 ────────────────────────────────────────────────────────────────────
stage "Netlify production deploy"
say "With builds still frozen, refresh cached origin/main and direct GitHub main; they must both equal DEPLOY_GIT_SHA."
git fetch --quiet origin main ||
  stop "Pre-Netlify source check failed while builds were frozen. Keep them frozen and restart from a newly reviewed main."
NETLIFY_TRACKING_SHA=$(git rev-parse origin/main) ||
  stop "Could not resolve cached origin/main while Netlify builds were frozen."
NETLIFY_REMOTE_SHA=$(git ls-remote origin refs/heads/main | awk 'NR == 1 { print $1 }') ||
  stop "Could not resolve direct GitHub main while Netlify builds were frozen."
[[ "$NETLIFY_TRACKING_SHA" == "$DEPLOY_GIT_SHA" &&
   "$NETLIFY_REMOTE_SHA" == "$DEPLOY_GIT_SHA" ]] ||
  stop "Pre-Netlify source check failed: main moved after review. Keep builds frozen and restart from the new clean merged main."
open_url "https://app.netlify.com/sites/$NETLIFY_PROJECT_SLUG/deploys"
step "Before any manual production deploy, use a fresh configuration/API read to require stop_builds=true, Deploy Previews disabled, and no deploy after baseline $NETLIFY_BASELINE_DEPLOY_ID."
confirm_or_stop "Are builds still stopped, previews disabled, and the deploy-history baseline unchanged?" \
  "Keep the site frozen and account for every unexpected deploy before continuing."
step "Authenticate the pinned Netlify CLI 27.4.2 in the operator terminal if needed, and verify it addresses only site ID $NETLIFY_SITE_ID. Do not create or save an automation token."
confirm_or_stop "Does the pinned CLI identify the intended Netlify account and exact site ID?" \
  "Do not deploy from an unauthenticated, wrong-account, or wrong-site CLI session."
docker info >/dev/null 2>&1 ||
  stop "Docker is not ready. Start the trusted local Docker engine before the frozen Linux release build."
case "$(uname -s)" in
  Darwin) NETLIFY_CONFIG_PATH="$HOME/Library/Preferences/netlify/config.json" ;;
  Linux) NETLIFY_CONFIG_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/netlify/config.json" ;;
  *) stop "The frozen Netlify release supports macOS or Linux operators only." ;;
esac
[[ -f "$NETLIFY_CONFIG_PATH" && ! -L "$NETLIFY_CONFIG_PATH" && -r "$NETLIFY_CONFIG_PATH" ]] ||
  stop "The interactive Netlify CLI credential file is missing, unreadable, or symbolic. Authenticate the pinned CLI without creating an automation token."
NETLIFY_RELEASE_PARENT=$(mktemp -d)
NETLIFY_RELEASE_DIR="$NETLIFY_RELEASE_PARENT/release"
NETLIFY_RELEASE_VOLUME=""
NETLIFY_RELEASE_VOLUME_CREATED="false"
cleanup_netlify_release() {
  local cleanup_failed=0 cleanup_volume_label=""
  if [[ "${NETLIFY_RELEASE_VOLUME_CREATED:-false}" == "true" &&
        -n "${NETLIFY_RELEASE_VOLUME:-}" &&
        "$NETLIFY_RELEASE_VOLUME" =~ ^[a-f0-9]{64}$ ]]; then
    if cleanup_volume_label=$(docker volume inspect \
      --format '{{ index .Labels "org.worldbank.dar-studio.release" }}' \
      "$NETLIFY_RELEASE_VOLUME" 2>/dev/null); then
      if [[ "$cleanup_volume_label" != "$DEPLOY_GIT_SHA" ]]; then
        warn "Temporary Linux release volume ownership could not be verified: $NETLIFY_RELEASE_VOLUME"
        cleanup_failed=1
      elif docker volume rm -f "$NETLIFY_RELEASE_VOLUME" >/dev/null 2>&1; then
        NETLIFY_RELEASE_VOLUME_CREATED="false"
      else
        warn "Temporary Linux release volume survived cleanup: $NETLIFY_RELEASE_VOLUME"
        cleanup_failed=1
      fi
    else
      warn "Could not verify cleanup of temporary Linux release volume: $NETLIFY_RELEASE_VOLUME"
      cleanup_failed=1
    fi
  fi
  if [[ -n "${NETLIFY_RELEASE_DIR:-}" && -e "$NETLIFY_RELEASE_DIR/.git" ]]; then
    if ! git worktree remove --force "$NETLIFY_RELEASE_DIR" >/dev/null 2>&1; then
      warn "Temporary release worktree survived cleanup: $NETLIFY_RELEASE_DIR"
      cleanup_failed=1
    fi
  fi
  if [[ -n "${NETLIFY_RELEASE_PARENT:-}" && -d "$NETLIFY_RELEASE_PARENT" ]]; then
    if ! rmdir "$NETLIFY_RELEASE_PARENT" >/dev/null 2>&1; then
      warn "Temporary release parent survived cleanup: $NETLIFY_RELEASE_PARENT"
      cleanup_failed=1
    fi
  fi
  return "$cleanup_failed"
}
trap 'cleanup_netlify_release || true' EXIT
trap 'exit 130' HUP INT TERM
git worktree add --detach "$NETLIFY_RELEASE_DIR" "$DEPLOY_GIT_SHA" ||
  stop "Could not create the clean detached worktree for the exact reviewed commit."
[[ "$(git -C "$NETLIFY_RELEASE_DIR" rev-parse HEAD)" == "$DEPLOY_GIT_SHA" &&
   -z "$(git -C "$NETLIFY_RELEASE_DIR" status --porcelain --untracked-files=all)" ]] ||
  stop "The detached Netlify release worktree is not the exact clean reviewed commit."
NETLIFY_RELEASE_VOLUME=$(docker volume create \
  --label "org.worldbank.dar-studio.release=$DEPLOY_GIT_SHA") ||
  stop "Could not create the temporary Linux release volume."
[[ "$NETLIFY_RELEASE_VOLUME" =~ ^[a-f0-9]{64}$ ]] ||
  stop "Docker returned an invalid temporary release volume identifier."
NETLIFY_RELEASE_VOLUME_CREATED="true"
NETLIFY_RELEASE_VOLUME_LABEL=$(docker volume inspect \
  --format '{{ index .Labels "org.worldbank.dar-studio.release" }}' \
  "$NETLIFY_RELEASE_VOLUME") ||
  stop "Could not verify ownership of the temporary Linux release volume."
[[ "$NETLIFY_RELEASE_VOLUME_LABEL" == "$DEPLOY_GIT_SHA" ]] ||
  stop "The temporary Linux release volume ownership label is invalid."
unset NETLIFY_RELEASE_VOLUME_LABEL
say "Install the exact locked dependency tree without any operator secret inside the pinned Linux/amd64 image. The later build and deploy reuse only this ephemeral volume."
docker run --rm --platform linux/amd64 \
  --mount "type=bind,source=$NETLIFY_RELEASE_DIR,target=/source,readonly" \
  --mount "type=volume,source=$NETLIFY_RELEASE_VOLUME,target=/workspace" \
  "$NETLIFY_RELEASE_IMAGE" bash -ceu '
    [[ -z "$(find /workspace -mindepth 1 -maxdepth 1 -print -quit)" ]]
    shopt -s dotglob nullglob
    cp -a /source/. /workspace/
    rm -f /workspace/.git
    cd /workspace
    [[ "$(uname -s)" == "Linux" && "$(uname -m)" == "x86_64" ]]
    [[ "$(node --version)" == "v22.22.3" ]]
    npm ci
    [[ "$(node -p "require(\"./node_modules/netlify-cli/package.json\").version")" == "27.4.2" ]]
    [[ "$(node -p "require(\"./node_modules/@netlify/zip-it-and-ship-it/package.json\").version")" == "15.5.0" ]]
  ' || stop "The secretless, pinned Linux/amd64 dependency installation failed."
say "Build the exact release with the already-held operator values, inspect a separately packaged Linux function archive, then let the same pinned Linux CLI package and upload once."
NETLIFY_DEPLOY_STATUS=0
if (
  # This shell may have been started after an operator sourced a credential file.
  # Strip every inherited export before the Docker client runs, then restore only
  # its small process environment and explicitly allowlist release values by name.
  while IFS= read -r RELEASE_EXPORTED_NAME; do
    export -n "$RELEASE_EXPORTED_NAME" 2>/dev/null || true
  done < <(compgen -e)
  for RELEASE_BASE_NAME in \
    PATH HOME TMPDIR LANG LC_ALL TERM \
    DOCKER_HOST DOCKER_CONTEXT DOCKER_CONFIG DOCKER_TLS_VERIFY \
    DOCKER_CERT_PATH SSH_AUTH_SOCK; do
    [[ -n "${!RELEASE_BASE_NAME:-}" ]] && export "$RELEASE_BASE_NAME"
  done
  unset EXA_API_KEY
  unset JINA_API_KEY
  unset PERPLEXITY_API_KEY
  unset ANTHROPIC_API_KEY
  unset OPENAI_API_KEY
  unset GEMINI_API_KEY
  unset RESEND_API_KEY
  unset XAI_API_KEY
  unset GH_TOKEN
  unset GITHUB_TOKEN
  unset NETLIFY_AUTH_TOKEN
  unset NPM_TOKEN
  unset NODE_AUTH_TOKEN

  MIGRATION_DATABASE_URL="$DATABASE_URL_DIRECT"
  if [[ "$AUTH_MODE" == "broker" ]]; then
    RELEASE_GROK_AUTH_ISSUER="$GROK_AUTH_ISSUER"
    RELEASE_GROK_AUTH_CLIENT_ID="$GROK_AUTH_CLIENT_ID"
    RELEASE_GROK_AUTH_CLIENT_SECRET="$GROK_AUTH_CLIENT_SECRET"
  else
    RELEASE_GROK_AUTH_ISSUER=""
    RELEASE_GROK_AUTH_CLIENT_ID=""
    RELEASE_GROK_AUTH_CLIENT_SECRET=""
  fi

  docker info >/dev/null 2>&1 ||
    stop "The selected Docker engine changed or became unavailable before the release build."
  printf '%s\0' \
    "$NETLIFY_SITE_ID" \
    "$DEPLOY_GIT_SHA" \
    "$AUTH_MODE" \
    "$DATABASE_URL" \
    "$MIGRATION_DATABASE_URL" \
    "$DAR_KEY_SECRET" \
    "$BETTER_AUTH_SECRET" \
    "$ARTIFACT_DELIVERY_SECRET" \
    "$BETTER_AUTH_URL" \
    "$VITE_PUBLIC_HOSTNAME" \
    "$ARTIFACT_GATEWAY_URL" \
    "$VITE_AUTH_ENABLED" \
    "$VITE_GROK_AUTH_ENABLED" \
    "$RELEASE_GROK_AUTH_ISSUER" \
    "$RELEASE_GROK_AUTH_CLIENT_ID" \
    "$RELEASE_GROK_AUTH_CLIENT_SECRET" |
    docker run --rm -i --platform linux/amd64 \
      --mount "type=volume,source=$NETLIFY_RELEASE_VOLUME,target=/workspace" \
      "$NETLIFY_RELEASE_IMAGE" bash -ceu '
      read_release_value() {
        local target="$1"
        IFS= read -r -d "" "$target" || exit 64
      }
      for release_name in \
        NETLIFY_SITE_ID DEPLOY_GIT_SHA AUTH_MODE \
        DATABASE_URL MIGRATION_DATABASE_URL \
        DAR_KEY_SECRET BETTER_AUTH_SECRET ARTIFACT_DELIVERY_SECRET \
        BETTER_AUTH_URL VITE_PUBLIC_HOSTNAME ARTIFACT_GATEWAY_URL \
        VITE_AUTH_ENABLED VITE_GROK_AUTH_ENABLED \
        GROK_AUTH_ISSUER GROK_AUTH_CLIENT_ID GROK_AUTH_CLIENT_SECRET; do
        read_release_value "$release_name"
      done
      unset release_name

      cd /workspace || exit $?
      [[ "$(uname -s)" == "Linux" && "$(uname -m)" == "x86_64" ]]
      [[ "$(node --version)" == "v22.22.3" ]]

      NETLIFY="true"
      CONTEXT="production"
      BRANCH="main"
      COMMIT_REF="$DEPLOY_GIT_SHA"
      EXPECTED_DEPLOY_GIT_SHA="$DEPLOY_GIT_SHA"
      export NETLIFY CONTEXT BRANCH COMMIT_REF EXPECTED_DEPLOY_GIT_SHA
      export DATABASE_URL MIGRATION_DATABASE_URL
      export DAR_KEY_SECRET BETTER_AUTH_SECRET ARTIFACT_DELIVERY_SECRET
      export BETTER_AUTH_URL VITE_PUBLIC_HOSTNAME ARTIFACT_GATEWAY_URL
      export VITE_AUTH_ENABLED VITE_GROK_AUTH_ENABLED
      if [[ "$AUTH_MODE" == "broker" ]]; then
        export GROK_AUTH_ISSUER GROK_AUTH_CLIENT_ID GROK_AUTH_CLIENT_SECRET
      fi

      npm run build

      RELEASE_SECRET_NAMES=(
        DATABASE_URL
        MIGRATION_DATABASE_URL
        DAR_KEY_SECRET
        BETTER_AUTH_SECRET
        ARTIFACT_DELIVERY_SECRET
      )
      if [[ "$AUTH_MODE" == "broker" ]]; then
        RELEASE_SECRET_NAMES+=(GROK_AUTH_CLIENT_SECRET)
      fi
      node scripts/verify-build-no-secrets.mjs "${RELEASE_SECRET_NAMES[@]}"

      unset DATABASE_URL MIGRATION_DATABASE_URL
      unset DAR_KEY_SECRET BETTER_AUTH_SECRET ARTIFACT_DELIVERY_SECRET
      unset GROK_AUTH_ISSUER GROK_AUTH_CLIENT_ID GROK_AUTH_CLIENT_SECRET
      unset NETLIFY CONTEXT BRANCH COMMIT_REF EXPECTED_DEPLOY_GIT_SHA
      unset BETTER_AUTH_URL VITE_PUBLIC_HOSTNAME ARTIFACT_GATEWAY_URL
      unset VITE_AUTH_ENABLED VITE_GROK_AUTH_ENABLED

      for unexpected_deploy_input in \
        netlify/functions \
        .netlify/functions \
        .netlify/functions-internal \
        .netlify/edge-functions \
        .netlify/v1/edge-functions \
        .netlify/edge-functions-dist \
        .netlify/v1/blobs \
        .netlify/deploy/v1/blobs \
        .netlify/blobs \
        .netlify/deploy-config \
        .netlify/internal/db/migrations; do
        [[ ! -e "$unexpected_deploy_input" ]] || exit 65
      done
      unset unexpected_deploy_input
      node scripts/verify-netlify-function-bundle.mjs
    ' || exit $?

  printf '%s\0' "$NETLIFY_SITE_ID" "$DEPLOY_GIT_SHA" |
    docker run --rm -i --platform linux/amd64 \
      --mount "type=volume,source=$NETLIFY_RELEASE_VOLUME,target=/workspace" \
      --mount "type=bind,source=$NETLIFY_CONFIG_PATH,target=/netlify-auth/config.json,readonly" \
      --tmpfs /root/.config/netlify:rw,noexec,nosuid,nodev,mode=0700 \
      "$NETLIFY_RELEASE_IMAGE" bash -ceu '
      read_release_value() {
        local target="$1"
        IFS= read -r -d "" "$target" || exit 64
      }
      for release_name in NETLIFY_SITE_ID DEPLOY_GIT_SHA; do
        read_release_value "$release_name"
      done
      unset release_name

      cd /workspace || exit $?
      [[ "$(uname -s)" == "Linux" && "$(uname -m)" == "x86_64" ]]
      [[ "$(node --version)" == "v22.22.3" ]]
      [[ "$(node -p "require(\"./node_modules/netlify-cli/package.json\").version")" == "27.4.2" ]]
      [[ "$(node -p "require(\"./node_modules/@netlify/zip-it-and-ship-it/package.json\").version")" == "15.5.0" ]]
      install -m 600 /netlify-auth/config.json /root/.config/netlify/config.json

      AWS_LAMBDA_JS_RUNTIME="nodejs22.x"
      NETLIFY_RUNTIME_JSON=$(./node_modules/.bin/netlify env:get AWS_LAMBDA_JS_RUNTIME --context dev --scope functions --site "$NETLIFY_SITE_ID" --json)
      NETLIFY_REMOTE_RUNTIME=$(printf "%s" "$NETLIFY_RUNTIME_JSON" | node -e "const fs=require(\"node:fs\"); const parsed=JSON.parse(fs.readFileSync(0,\"utf8\")); process.stdout.write(parsed.AWS_LAMBDA_JS_RUNTIME ?? \"\")")
      [[ "$NETLIFY_REMOTE_RUNTIME" == "$AWS_LAMBDA_JS_RUNTIME" ]]
      unset NETLIFY_RUNTIME_JSON

      ./node_modules/.bin/netlify deploy --prod --no-build --skip-functions-cache \
        --dir dist/client --functions .netlify/v1/functions \
        --site "$NETLIFY_SITE_ID" --message "DAR Studio release $DEPLOY_GIT_SHA"
    '
); then
  NETLIFY_DEPLOY_STATUS=0
else
  NETLIFY_DEPLOY_STATUS=$?
fi
cleanup_netlify_release ||
  stop "The temporary Netlify release state could not be removed safely. Resolve it before recording a successful deploy."
[[ ! -e "$NETLIFY_RELEASE_DIR" ]] ||
  warn "The exact temporary release worktree needs manual cleanup at $NETLIFY_RELEASE_DIR."
trap - EXIT HUP INT TERM
(( NETLIFY_DEPLOY_STATUS == 0 )) ||
  stop "The exact manual Netlify production deploy failed. Builds remain stopped; inspect the failed manual attempt before any retry."
step "Require [deploy-preflight] success with Netlify CONTEXT=production, BRANCH=main, and COMMIT_REF exactly equal to EXPECTED_DEPLOY_GIT_SHA=$DEPLOY_GIT_SHA before Vite or migration starts. Require the migration advisory lock and an up-to-date exact 30-row ledger through 0030. Netlify must not be the first process to apply 0030."
step "Require the Netlify adapter output, not .vercel output. Open /, /methodology, and /login over HTTPS."
step "Require the deployed server Function metadata to show Node.js 22.x and streamed invocation; any Node 24.x runtime is a hard stop."
step "Confirm email auth works and Google/X visibility exactly matches VITE_GROK_AUTH_ENABLED."
step "Confirm app-owned loading, error, empty, dialog, and page states retain the explicit white background."
step "Confirm both artifact-gateway values reached Functions. The first authenticated JSON-grant and header-only byte-delivery proof occurs in Stage 16 after a real artifact exists."
ask NETLIFY_DEPLOY_ID "Successful Netlify production deploy ID:"
require_value NETLIFY_DEPLOY_ID "$NETLIFY_DEPLOY_ID"
NETLIFY_DEPLOY_SHA="$DEPLOY_GIT_SHA"
step "Require the successful deploy to be Manual, Production, and titled exactly DAR Studio release $DEPLOY_GIT_SHA. Manual deploy metadata may omit commit_ref; exactness comes from the clean detached worktree plus the preflight-bound COMMIT_REF."
write_env NETLIFY_DEPLOY_ID "$NETLIFY_DEPLOY_ID"
write_env NETLIFY_DEPLOY_SHA "$NETLIFY_DEPLOY_SHA"
confirm_or_stop "Did every web, configuration, and fail-closed check pass without a usable PGLite-backed deployment?" \
  "The web deployment is not ready for workflow smoke testing."
step "Use one final fresh read to require stop_builds=true, Deploy Previews disabled, and exactly one new manual production deploy after the recorded baseline."
confirm_or_stop "Did the build freeze remain closed and did exactly one intended manual production deploy occur?" \
  "Account for any extra deploy before closing the release."

stage "Deployment-only closeout boundary"
step "Record exact DAR on Netlify/gateway/worker, DAMM $DAMM_SOURCE_COMMIT, node=22.22.3, python=3.12.13, migrations=30 through 0030, private anonymous denial plus authorized access, every automation freeze, zero active workflows, and the unchanged preserved failures."
warn "Stop here unless post-deployment identity setup and the separately authorized paid canary are explicitly in scope. Deployment completion does not authorize either."
if ! confirm "Are the post-deployment human test identities and one separately authorized named-country paid canary explicitly in scope now?"; then
  DEPLOYMENT_DEPLOYED_AT_UTC=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  write_env DEPLOYMENT_DEPLOYED_AT_UTC "$DEPLOYMENT_DEPLOYED_AT_UTC"
  write_env DEPLOYMENT_READINESS_STATUS "deployed-no-canary"
  chmod 600 "$ENV_FILE"
  finish
  say "Deployment-only closeout is complete. No identities, country workspace, or paid run were created."
  exit 0
fi

# ── 15 ────────────────────────────────────────────────────────────────────
stage "Three registered human identities"
open_url "$NETLIFY_URL/login"
say "Create three distinct Better Auth accounts. Store their passwords in your password manager; this wizard records names/emails only."
ask SMOKE_OWNER_NAME "Country owner / G3 signer name:"
require_value SMOKE_OWNER_NAME "$SMOKE_OWNER_NAME"
ask SMOKE_OWNER_EMAIL "Country owner email:"
require_email SMOKE_OWNER_EMAIL "$SMOKE_OWNER_EMAIL"
ask SMOKE_G1_NAME "G1 assessor name:"
require_value SMOKE_G1_NAME "$SMOKE_G1_NAME"
ask SMOKE_G1_EMAIL "G1 assessor email:"
require_email SMOKE_G1_EMAIL "$SMOKE_G1_EMAIL"
ask SMOKE_G2_NAME "Independent G2 reviewer name:"
require_value SMOKE_G2_NAME "$SMOKE_G2_NAME"
ask SMOKE_G2_EMAIL "Independent G2 reviewer email:"
require_email SMOKE_G2_EMAIL "$SMOKE_G2_EMAIL"
[[ "$SMOKE_OWNER_EMAIL" != "$SMOKE_G1_EMAIL" &&
   "$SMOKE_OWNER_EMAIL" != "$SMOKE_G2_EMAIL" &&
   "$SMOKE_G1_EMAIL" != "$SMOKE_G2_EMAIL" ]] ||
  stop "Owner, G1, and G2 must be three different registered accounts."
write_env SMOKE_OWNER_NAME "$SMOKE_OWNER_NAME"
write_env SMOKE_OWNER_EMAIL "$SMOKE_OWNER_EMAIL"
write_env SMOKE_G1_NAME "$SMOKE_G1_NAME"
write_env SMOKE_G1_EMAIL "$SMOKE_G1_EMAIL"
write_env SMOKE_G2_NAME "$SMOKE_G2_NAME"
write_env SMOKE_G2_EMAIL "$SMOKE_G2_EMAIL"
step "Sign out and sign back in as each account. Email verification is not required; password recovery is not proven without Resend."
confirm_or_stop "Did all three exact registered identities authenticate successfully?" \
  "Human controls cannot be tested with shared, demo, or unregistered identities."

# ── 16 ────────────────────────────────────────────────────────────────────
stage "Autonomous eight-stage Draft and artifact smoke"
warn "This stage is outside deployment and consumes vendor budget. Stop here unless a separate explicit paid-canary authorization names one new country; country must remain the only required launch input."
confirm_or_stop "Is one complete eight-stage staging workflow for a specifically named country separately authorized now?" \
  "Do not launch without explicit vendor-spend authority."
step "Reverify every selected provider model ID and tariff against first-party documentation today. Map the exact Render Jina key to its package/rate; verify its account funding control is acceptably bounded for the canary and record provider-side spend limits where available."
step "Require exact DAR on Netlify/gateway/worker, DAMM $DAMM_SOURCE_COMMIT, 38-file identity 61d78ea4ff58c69b21591a997f34f71e1748859ae317910806e1cdf985856f39, expected model/renderer hashes, migrations=30 through 0030, and no unresolved spend reservation."
step "Require exactly one Live worker instance and possible claimant with confirmed lease margin; zero active workflows; all eight preserved failures unchanged; stopped Netlify builds after the exact deploy; Deploy Previews off; Render automatic deploys off; Blueprint disconnected with no Sync Hook; private anonymous denial; and authorized reachability."
confirm_or_stop "Are every same-day tariff, account-funding, identity, singleton, lease, zero-active, preserved-failure, and automation-freeze prelaunch gate recorded and green?" \
  "A missing or uncertain paid-canary precondition is NO-GO. Do not create a country workspace."
ask SMOKE_CEILING_USD "Explicitly authorized positive run ceiling in USD, at most the remaining allowance:"
require_value SMOKE_CEILING_USD "$SMOKE_CEILING_USD"
confirm_or_stop 'Has the chosen positive spend limit been reserved within the remaining cumulative allowance?' \
  'Reconcile settled charges and unresolved reservations first. Record the selected ceiling before creating a workspace or launching.'
ask SMOKE_COUNTRY_NAME "Explicitly authorized canary country name:"
require_value SMOKE_COUNTRY_NAME "$SMOKE_COUNTRY_NAME"
step "As the owner, create exactly one new $SMOKE_COUNTRY_NAME country workspace, leave all optional upload categories empty, set the spend limit to $SMOKE_CEILING_USD, and click Launch Draft DAR workflow once. Verify the stored run ceiling equals the reserved amount; do not launch another run if it differs. Never retry, resume, or reuse a historical failed run; capture the new run ID and artifact-set identity."
step "At launch and after every stage, record sole claimant/lease margin, immutable publication and input/output hashes, settled spend plus unresolved reservations by provider/model/pass, and cumulative spend against 45%, 52.5%, 62.5%, 70%, 80%, 85%, then strictly below 100% of the selected run ceiling. Stage 8 adds no provider cost."
step "Observe all eight stages. There must be no human input, review gate, pause, approval, budget top-up, provider/model switch, or automatic retry."
step "As each Stage 1-7 publication appears, require its owner-only report downloads to remain available while later stages run; anonymous and reviewer-only accounts must be denied."
step "At completion require Draft · pre-review and explicit wording that automation is not G1/G2/G3 or publication readiness."
step "Download the bundle, Draft MD/DOCX/PDF, cost-benefit XLSX, source XLSX, manifests, and representative artifacts from every stage."
step "Use the largest real artifact from this run: require Netlify 200 + no-store delivery-grant JSON, with a fixed HTTPS /v1/artifacts endpoint and no capability in any URL."
step "Require the browser to send the capability only as Authorization: Bearer, without cookies, from APP_ORIGIN; gateway must return 200, private/no-store, filename, length, SHA header, and an exact body hash."
step "Require anonymous/unassigned denial at Netlify. In an ephemeral history-free client, change one header capability character and replay a separate untouched header capability after >60 seconds; both gateway responses must be the same non-disclosing 404."
step "Abort without automatic retry/top-up/state repair on identity, tariff, package, or funding drift; a second claimant or unconfirmed lease; missing/malformed/ambiguous/unmetered/over-reservation usage; any paid transport retry; technical failure presented as evidence absence; empty/stale/duplicate/truncated/semantically incomplete product; ledger/checkpoint mismatch; or publication/final-acknowledgement failure. Preserve the run for reconciliation."
step "During G1 reassignment, require a previously minted but unexpired capability for the superseded reviewer to fail at the gateway immediately."
step "The repository suite proves an exact synthetic >20 MiB 21-chunk stream plus wrong-package and changed-hash rejection. If this run naturally exceeds 20 MiB, record its live size/hash proof too; never mutate staging rows or distort the country-only workflow to manufacture it."
ask SMOKE_COUNTRY_ID "Smoke country ID:"
require_value SMOKE_COUNTRY_ID "$SMOKE_COUNTRY_ID"
ask SMOKE_RUN_ID "Completed workflow run ID:"
require_value SMOKE_RUN_ID "$SMOKE_RUN_ID"
ask SMOKE_ARTIFACT_SET_ID "Immutable artifact-set ID:"
require_value SMOKE_ARTIFACT_SET_ID "$SMOKE_ARTIFACT_SET_ID"
ask SMOKE_BUNDLE_SHA256 "Complete-bundle SHA-256:"
require_sha256 SMOKE_BUNDLE_SHA256 "$SMOKE_BUNDLE_SHA256"
ask SMOKE_WORKFLOW_CONTRACT_SHA256 "Workflow contract SHA-256:"
require_sha256 SMOKE_WORKFLOW_CONTRACT_SHA256 "$SMOKE_WORKFLOW_CONTRACT_SHA256"
ask SMOKE_DAMM_MODEL_SHA256 "DAMM model SHA-256:"
require_sha256 SMOKE_DAMM_MODEL_SHA256 "$SMOKE_DAMM_MODEL_SHA256"
ask SMOKE_ASSESSMENT_INPUT_SHA256 "Assessment-input SHA-256:"
require_sha256 SMOKE_ASSESSMENT_INPUT_SHA256 "$SMOKE_ASSESSMENT_INPUT_SHA256"
ask SMOKE_BUNDLE_BYTES "Downloaded bundle byte count:"
[[ "$SMOKE_BUNDLE_BYTES" =~ ^[0-9]+$ && "$SMOKE_BUNDLE_BYTES" -gt 0 ]] ||
  stop "Bundle byte count must be a positive integer."
ask SMOKE_GATEWAY_ARTIFACT_BYTES "Largest real artifact verified through the gateway, in bytes:"
[[ "$SMOKE_GATEWAY_ARTIFACT_BYTES" =~ ^[0-9]+$ && "$SMOKE_GATEWAY_ARTIFACT_BYTES" -gt 0 ]] ||
  stop "The real gateway artifact byte count must be a positive integer."
if [[ "$SMOKE_GATEWAY_ARTIFACT_BYTES" -gt 20971520 ]]; then
  SMOKE_LIVE_OVER_20_MIB="true"
else
  SMOKE_LIVE_OVER_20_MIB="false"
  say "This real package stayed below 20 MiB; the mandatory synthetic 21-chunk regression is the large-stream proof."
fi
write_env SMOKE_COUNTRY_ID "$SMOKE_COUNTRY_ID"
write_env SMOKE_COUNTRY_NAME "$SMOKE_COUNTRY_NAME"
write_env SMOKE_RUN_ID "$SMOKE_RUN_ID"
write_env SMOKE_ARTIFACT_SET_ID "$SMOKE_ARTIFACT_SET_ID"
write_env SMOKE_BUNDLE_SHA256 "$SMOKE_BUNDLE_SHA256"
write_env SMOKE_WORKFLOW_CONTRACT_SHA256 "$SMOKE_WORKFLOW_CONTRACT_SHA256"
write_env SMOKE_DAMM_MODEL_SHA256 "$SMOKE_DAMM_MODEL_SHA256"
write_env SMOKE_ASSESSMENT_INPUT_SHA256 "$SMOKE_ASSESSMENT_INPUT_SHA256"
write_env SMOKE_BUNDLE_BYTES "$SMOKE_BUNDLE_BYTES"
write_env SMOKE_GATEWAY_ARTIFACT_BYTES "$SMOKE_GATEWAY_ARTIFACT_BYTES"
write_env SMOKE_LIVE_OVER_20_MIB "$SMOKE_LIVE_OVER_20_MIB"
confirm_or_stop "Did every workflow, lifecycle, persistence, format, download, hash, and white-background check pass?" \
  "The completed Draft package did not satisfy staging acceptance."

# ── 17 ────────────────────────────────────────────────────────────────────
stage "Post-completion G1, G2, and G3"
open_url "$NETLIFY_URL"
step "As owner open Human controls. Before assignments require zero human decisions and a locked G3."
step "Temporarily assign pending G1 to $SMOKE_G2_EMAIL. Require its exact-package download access, while the still-unassigned $SMOKE_G1_EMAIL account is denied."
step "Replace that pending G1 assignment with $SMOKE_G1_EMAIL and a reason. Require the superseded account's new artifact request to be denied and the immutable supersession audit to remain visible."
step "Assign G2 to $SMOKE_G2_EMAIL. Require exact-package access again. Attempt to replace G2 with the active G1 account and require rejection."
step "Open G2 before G1: its frozen scope may be visible, but submission must be locked."
step "As G1 decide every machine-filled row, affirm the human role, and record the immutable G1 decision. Reopen it read-only."
step "As the distinct G2 reviewer independently decide every frozen-scope row, affirm, and record G2."
step "As owner confirm G3 unlocks only now, check all seven affirmations, and record the named/dated decision."
step "Require a versioned Approved Draft release; the unratified methodology must never yield Canonical Final. Original Draft downloads must remain unchanged."
ask SMOKE_PACKAGE_ID "Approval package ID:"
require_value SMOKE_PACKAGE_ID "$SMOKE_PACKAGE_ID"
ask SMOKE_TARGET_IDENTITY_SHA256 "Approval target-identity SHA-256:"
require_sha256 SMOKE_TARGET_IDENTITY_SHA256 "$SMOKE_TARGET_IDENTITY_SHA256"
ask SMOKE_G1_DECISION_ID "Immutable G1 decision ID:"
require_value SMOKE_G1_DECISION_ID "$SMOKE_G1_DECISION_ID"
ask SMOKE_G2_DECISION_ID "Immutable G2 decision ID:"
require_value SMOKE_G2_DECISION_ID "$SMOKE_G2_DECISION_ID"
ask SMOKE_G3_DECISION_ID "Immutable G3 decision ID:"
require_value SMOKE_G3_DECISION_ID "$SMOKE_G3_DECISION_ID"
ask SMOKE_RELEASE_ID "Versioned Approved Draft release ID:"
require_value SMOKE_RELEASE_ID "$SMOKE_RELEASE_ID"
write_env SMOKE_PACKAGE_ID "$SMOKE_PACKAGE_ID"
write_env SMOKE_TARGET_IDENTITY_SHA256 "$SMOKE_TARGET_IDENTITY_SHA256"
write_env SMOKE_G1_DECISION_ID "$SMOKE_G1_DECISION_ID"
write_env SMOKE_G2_DECISION_ID "$SMOKE_G2_DECISION_ID"
write_env SMOKE_G3_DECISION_ID "$SMOKE_G3_DECISION_ID"
write_env SMOKE_RELEASE_ID "$SMOKE_RELEASE_ID"
confirm_or_stop "Were G2 independence, early-G3 lock, immutable identities, Draft preservation, and honest release wording all enforced?" \
  "The human-control chain failed live acceptance."

# ── 18 ────────────────────────────────────────────────────────────────────
stage "Neon audit, immutability probe, and closeout"
open_url "https://console.neon.tech/app/projects/$NEON_PROJECT_ID"
step "In SQL Editor run the package/decision/release audit query from the deployment guide using $SMOKE_PACKAGE_ID."
step "Require three human actors, distinct G1/G2 user IDs, owner G3, one exact package/bundle identity, model_ratified=false, lifecycle approved_draft."
step "Run the assignment/supersession query. Require one inactive temporary G1 with one immutable supersession, plus the intended active completed G1 and independent G2."
step "Run the guide's zero-persistence DO-block update probe against G1 decision $SMOKE_G1_DECISION_ID. Require the immutable trigger, then re-query the unchanged identity."
step "Record the Netlify deploy and both separate Render service deploy IDs/commits, Neon project/branch/snapshot, run/package hashes, decision/release IDs, validation results, and UTC completion time."
step "Keep the pre-migration snapshot through acceptance. Rollback order is: block launches, settle runs, suspend both Render services, publish/lock the prior web deploy, then restore Neon only with explicit data-loss authority."
confirm_or_stop "Did the database audit and immutable identity probe pass exactly?" \
  "Do not close staging acceptance with an incomplete audit."
DEPLOYMENT_ACCEPTED_AT_UTC=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
write_env DEPLOYMENT_ACCEPTED_AT_UTC "$DEPLOYMENT_ACCEPTED_AT_UTC"
write_env DEPLOYMENT_READINESS_STATUS "accepted-staging"
chmod 600 "$ENV_FILE"

finish
say "Deployment evidence is in $ENV_FILE (mode 0600, gitignored)."
say "Keep staging Private. This acceptance does not claim DAMM ratification or a canonical Final release."
