#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=18

# The template defaults to .env. This deployment deliberately uses an ignored,
# environment-specific operator record unless the caller supplied ENV_FILE.
if [[ "$ENV_FILE" == ".env" ]]; then
  ENV_FILE=".env.staging"
fi
umask 077

stop() {
  printf '\n  %s%sSTOP:%s %s\n\n' "$BOLD" "$RED" "$RESET" "$1" >&2
  exit 1
}

confirm_or_stop() {
  confirm "$1" || stop "${2:-The required confirmation was not given.}"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || stop "Required command '$1' is not installed."
}

require_value() {
  local name="$1" value="$2"
  [[ -n "${value//[[:space:]]/}" ]] || stop "$name cannot be blank."
}

require_sha256() {
  local name="$1" value="$2"
  [[ "$value" =~ ^[a-f0-9]{64}$ ]] || stop "$name must be a lowercase 64-character SHA-256."
}

require_email() {
  local name="$1" value="$2"
  [[ "$value" =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ ]] ||
    stop "$name must be a valid email address."
}

remove_env() {
  local key="$1" tmp
  [[ -f "$ENV_FILE" ]] || return 0
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  mv "$tmp" "$ENV_FILE"
  printf '  %s✓ removed%s stale %s from %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

write_optional() {
  local key="$1" value="$2"
  if [[ -n "$value" ]]; then
    write_env "$key" "$value"
  else
    remove_env "$key"
  fi
}

generate_secret() {
  local key="$1" current
  current=$(_existing "$key" || true)
  if [[ -z "$current" ]]; then
    current=$(openssl rand -base64 48 | tr -d '\n')
  fi
  printf -v "$key" '%s' "$current"
  write_env "$key" "$current"
}

banner "DAR Studio · Ohio staging deployment"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Merged main and architectural stop checks"
say "Provision only from the merged main branch. The first checks avoid spending money on a topology that cannot meet the product contract."
require_command git
require_command node
require_command npm
require_command openssl

[[ -d .git && -f package.json ]] || stop "Run this wizard from the dar-studio-v2 repository root."
[[ "$(git branch --show-current)" == "main" ]] ||
  stop "Check out the merged main branch before provisioning."
[[ -z "$(git status --porcelain)" ]] ||
  stop "The worktree is not clean. Preserve or commit its changes before provisioning."

say "Refreshing the read-only view of origin/main…"
git fetch --quiet origin main || stop "Could not fetch origin/main. Check GitHub access and retry."
LOCAL_SHA=$(git rev-parse HEAD)
TRACKING_SHA=$(git rev-parse origin/main)
REMOTE_SHA=$(git ls-remote origin refs/heads/main | awk 'NR == 1 { print $1 }')
[[ "$LOCAL_SHA" == "$TRACKING_SHA" && "$LOCAL_SHA" == "$REMOTE_SHA" ]] ||
  stop "Local HEAD, origin/main, and the direct GitHub branch hash do not match."
DEPLOY_GIT_SHA="$LOCAL_SHA"
write_env DEPLOY_GIT_SHA "$DEPLOY_GIT_SHA"

required_files=(
  netlify.toml
  render.yaml
  Dockerfile.artifact-gateway
  Dockerfile.worker
  deploy/artifact-gateway/package.json
  deploy/artifact-gateway/package-lock.json
  deploy/worker/entrypoint.sh
  deploy/worker/preflight.mjs
  scripts/artifact-gateway.ts
  migrations/0013_damm_methodology_pin_cutover.sql
  docs/DEPLOYMENT-NETLIFY-NEON-RENDER-OHIO.md
)
for required_file in "${required_files[@]}"; do
  [[ -f "$required_file" ]] || stop "Merged deployment file $required_file is missing."
done
grep -q "name: dar-studio-artifacts" render.yaml || stop "render.yaml does not declare the artifact gateway."
grep -q "healthCheckPath: /healthz" render.yaml || stop "render.yaml does not declare the artifact gateway health check."
[[ "$(grep -c "region: ohio" render.yaml)" -eq 2 ]] || stop "render.yaml does not pin both Render services to Ohio."
[[ "$(grep -c "plan: 1c-2g" render.yaml)" -eq 2 ]] || stop "render.yaml does not pin both Render services to plan 1c-2g."
[[ "$(grep -c "autoDeployTrigger: off" render.yaml)" -eq 2 ]] || stop "render.yaml must disable automatic deploys for both services."
[[ "$(grep -c "numInstances: 1" render.yaml)" -eq 2 ]] || stop "render.yaml must declare one instance of each service."
[[ "$(grep -c "maxShutdownDelaySeconds: 300" render.yaml)" -eq 2 ]] || stop "render.yaml must grant both services a 300-second shutdown delay."
grep -q "type: worker" render.yaml || stop "render.yaml does not declare a background worker."
grep -q "type: web" render.yaml || stop "render.yaml does not declare an artifact web service."
grep -q "dockerfilePath: ./Dockerfile.worker" render.yaml || stop "render.yaml does not pin the worker Dockerfile."
grep -q "dockerfilePath: ./Dockerfile.artifact-gateway" render.yaml || stop "render.yaml does not pin the gateway Dockerfile."
grep -q "name: dar-studio-worker-data" render.yaml || stop "render.yaml does not declare the worker disk."
grep -q "mountPath: /var/data" render.yaml || stop "render.yaml does not mount the worker disk at /var/data."
grep -q "sizeGB: 10" render.yaml || stop "render.yaml does not pin the worker disk to 10 GB."
for render_key in DATABASE_URL ARTIFACT_DELIVERY_SECRET APP_ORIGIN EXA_API_KEY JINA_API_KEY PERPLEXITY_API_KEY ANTHROPIC_API_KEY OPENAI_API_KEY GEMINI_API_KEY; do
  grep -q "key: $render_key" render.yaml || stop "render.yaml is missing required environment key $render_key."
done
[[ "$(grep -c "key: DATABASE_URL" render.yaml)" -eq 2 ]] || stop "Both Render services must receive their own pooled DATABASE_URL."
grep -q "MIGRATION_DATABASE_URL" scripts/migrate.mjs ||
  stop "The migrator does not separate the direct migration URL from pooled runtime DATABASE_URL."
grep -qi "advisory" scripts/migrate.mjs ||
  stop "The deploy migrator has no visible Postgres advisory-lock guard."
grep -Rq "refusing the ephemeral PGLite fallback" src/lib ||
  stop "Hosted execution is not visibly configured to fail closed without DATABASE_URL."
grep -Rq "VITE_GROK_AUTH_ENABLED" src/lib src/routes scripts ||
  stop "The deployed social-auth gate is missing."
grep -q "ARTIFACT_DELIVERY_ENDPOINT_PATH" src/lib/damm-v17/artifact-delivery.ts ||
  stop "The Netlify artifact grant does not use the fixed gateway endpoint contract."
grep -q "ARTIFACT_DELIVERY_ENDPOINT_PATH" scripts/artifact-gateway.ts ||
  stop "The Render gateway does not use the fixed artifact endpoint contract."

confirm_or_stop "Run the complete local validation suite now?" \
  "A deployment must not proceed without repository validation."
npm test
npm run typecheck
npm run lint
npm run build:dev
npm run verify:netlify
say "Local validation passed at $DEPLOY_GIT_SHA."
pause "Continue to account and cost authorization?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Provider access and cost authorization"
say "Both Render 1c-2g services and the worker's persistent disk are billed. Live vendor checks and a complete DAR workflow also consume paid APIs."
open_url "https://app.netlify.com/"
open_url "https://console.neon.tech/app/projects"
open_url "https://dashboard.render.com/"
step "Confirm you can administer all three accounts, view usage, and rotate their credentials."
step "Confirm GitHub access to the exact dar-studio-v2 repository from Netlify and Render."
confirm_or_stop \
  "Are you authorized to create the Neon project, both paid Render services, the worker disk, and run vendor-cost smoke tests?" \
  "Cost authority is required before any cloud resource is created."
write_env DEPLOYMENT_ENVIRONMENT "staging"
pause "Provider access and cost authority are recorded?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Worker vendor credentials"
say "The country must remain the only required launch input, so all platform vendor keys must exist before the worker starts. Input is hidden and the local file is mode 0600."
open_url "https://dashboard.exa.ai/api-keys"
ask_secret EXA_API_KEY "Paste the Exa API key:"
require_value EXA_API_KEY "$EXA_API_KEY"
write_env EXA_API_KEY "$EXA_API_KEY"

open_url "https://jina.ai/api-dashboard/key-manager"
ask_secret JINA_API_KEY "Paste the Jina API key:"
require_value JINA_API_KEY "$JINA_API_KEY"
write_env JINA_API_KEY "$JINA_API_KEY"

open_url "https://www.perplexity.ai/settings/api"
ask_secret PERPLEXITY_API_KEY "Paste the Perplexity API key:"
require_value PERPLEXITY_API_KEY "$PERPLEXITY_API_KEY"
write_env PERPLEXITY_API_KEY "$PERPLEXITY_API_KEY"

open_url "https://console.anthropic.com/settings/keys"
ask_secret ANTHROPIC_API_KEY "Paste the Anthropic API key:"
require_value ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"

open_url "https://platform.openai.com/api-keys"
ask_secret OPENAI_API_KEY "Paste the OpenAI API key:"
require_value OPENAI_API_KEY "$OPENAI_API_KEY"
write_env OPENAI_API_KEY "$OPENAI_API_KEY"

open_url "https://aistudio.google.com/app/apikey"
ask_secret GEMINI_API_KEY "Paste the Gemini API key:"
require_value GEMINI_API_KEY "$GEMINI_API_KEY"
write_env GEMINI_API_KEY "$GEMINI_API_KEY"
chmod 600 "$ENV_FILE"
step "Do not commit, print, or import this whole file into either cloud dashboard. Each platform receives only its own keys."
pause "All six worker credentials are present?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Neon project in AWS Ohio"
open_url "https://console.neon.tech/app/projects"
step "Click New Project. Name it dar-studio-staging (or another staging-only name)."
step "Choose AWS and US East (Ohio), region ID aws-us-east-2. Do not accept the current N. Virginia default."
step "Create the project, then select its root production branch. Do not use the child development branch."
ask NEON_PROJECT_NAME "Neon project name:"
require_value NEON_PROJECT_NAME "$NEON_PROJECT_NAME"
ask NEON_PROJECT_ID "Neon project ID:"
require_value NEON_PROJECT_ID "$NEON_PROJECT_ID"
ask NEON_BRANCH_ID "Neon production branch ID:"
require_value NEON_BRANCH_ID "$NEON_BRANCH_ID"
ask NEON_DATABASE_NAME "Neon database name (normally neondb):"
require_value NEON_DATABASE_NAME "$NEON_DATABASE_NAME"
ask NEON_ROLE_NAME "Neon database role used by both connection strings:"
require_value NEON_ROLE_NAME "$NEON_ROLE_NAME"
NEON_REGION="aws-us-east-2"
NEON_BRANCH="production"
write_env NEON_PROJECT_NAME "$NEON_PROJECT_NAME"
write_env NEON_PROJECT_ID "$NEON_PROJECT_ID"
write_env NEON_REGION "$NEON_REGION"
write_env NEON_BRANCH "$NEON_BRANCH"
write_env NEON_BRANCH_ID "$NEON_BRANCH_ID"
write_env NEON_DATABASE_NAME "$NEON_DATABASE_NAME"
write_env NEON_ROLE_NAME "$NEON_ROLE_NAME"
confirm_or_stop "Does Neon show AWS US East (Ohio) / aws-us-east-2 and a parentless production branch?" \
  "The Neon region and root branch are immutable safety choices for this deployment."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Pooled runtime and direct migration URLs"
say "In the Neon project Dashboard click Connect. Select production and the intended database/role."
step "Turn Connection pooling on. Copy the URL whose hostname contains -pooler."
ask_secret DATABASE_URL "Paste the pooled Neon DATABASE_URL:"
require_value DATABASE_URL "$DATABASE_URL"
[[ "$DATABASE_URL" == postgres://* || "$DATABASE_URL" == postgresql://* ]] ||
  stop "DATABASE_URL must be a postgres:// or postgresql:// URL."
[[ "$DATABASE_URL" == *"-pooler.us-east-2.aws.neon.tech"* ]] ||
  stop "The pooled URL must contain -pooler and the Neon Ohio hostname."
[[ "$DATABASE_URL" == *"sslmode=require"* ]] ||
  stop "The pooled DATABASE_URL must include sslmode=require."
write_env DATABASE_URL "$DATABASE_URL"

step "Turn Connection pooling off and copy the direct URL."
ask_secret DATABASE_URL_DIRECT "Paste the direct Neon migration URL:"
require_value DATABASE_URL_DIRECT "$DATABASE_URL_DIRECT"
[[ "$DATABASE_URL_DIRECT" == postgres://* || "$DATABASE_URL_DIRECT" == postgresql://* ]] ||
  stop "DATABASE_URL_DIRECT must be a postgres:// or postgresql:// URL."
[[ "$DATABASE_URL_DIRECT" == *".us-east-2.aws.neon.tech"* ]] ||
  stop "The direct URL is not in Neon AWS Ohio."
[[ "$DATABASE_URL_DIRECT" != *-pooler.* ]] ||
  stop "DATABASE_URL_DIRECT unexpectedly contains -pooler."
[[ "$DATABASE_URL_DIRECT" == *"sslmode=require"* ]] ||
  stop "The direct DATABASE_URL_DIRECT must include sslmode=require."
[[ "$DATABASE_URL" != "$DATABASE_URL_DIRECT" ]] ||
  stop "Pooled DATABASE_URL and direct DATABASE_URL_DIRECT must be different connection strings."
write_env DATABASE_URL_DIRECT "$DATABASE_URL_DIRECT"
chmod 600 "$ENV_FILE"
say "Pooled: Netlify Build+Functions and both Render services. Direct: local migration and Netlify Build-only MIGRATION_DATABASE_URL."
pause "Both URLs were copied from the same production branch, database, and role?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Migration preflight and recovery snapshot"
open_url "https://console.neon.tech/app/projects/$NEON_PROJECT_ID"
step "Open SQL Editor; select production and the intended database."
say "Run: select to_regclass('public.runs') as runs_table;"
say "If it is non-null, run the active-workflow query in docs/DEPLOYMENT-NETLIFY-NEON-RENDER-OHIO.md."
confirm_or_stop "Did the active-workflow query return zero rows?" \
  "Do not migrate while any workflow is queued, running, or otherwise nonterminal."
step "Open Backup & Restore, enable Enhanced view if shown, select the root production branch, and click Create snapshot."
step "Name it with UTC time and the deploy commit, for example pre-0013-YYYYMMDD-HHMM-${DEPLOY_GIT_SHA:0:8}."
ask NEON_SNAPSHOT_NAME "Exact pre-migration snapshot name:"
require_value NEON_SNAPSHOT_NAME "$NEON_SNAPSHOT_NAME"
write_env NEON_SNAPSHOT_NAME "$NEON_SNAPSHOT_NAME"
confirm_or_stop "Is that snapshot complete and visibly tied to the root production branch?" \
  "A recoverable snapshot is required before migration."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Apply and verify migration 0013"
warn "This is the first database mutation. The direct URL is used, and the migrator takes its Postgres advisory lock."
confirm_or_stop "Run the idempotent migration set against this Neon staging database now?" \
  "Migration was not authorized. No worker may be deployed yet."
DATABASE_URL="$DATABASE_URL" MIGRATION_DATABASE_URL="$DATABASE_URL_DIRECT" npm run db:migrate ||
  stop "Migration failed. Keep the snapshot, read the exact error, and do not deploy the worker."
open_url "https://console.neon.tech/app/projects/$NEON_PROJECT_ID"
step "In SQL Editor, query _migrations for 0013_damm_methodology_pin_cutover.sql. Require exactly one row."
step "Run the function checks in the guide. Require pinned_commit=true and remains_unratified=true."
confirm_or_stop "Did both migration verification queries return the exact expected result?" \
  "A worker cannot start on an unverified schema or methodology pin."
write_env MIGRATION_0013_VERIFIED "true"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Import the main branch into Netlify"
open_url "https://app.netlify.com/"
step "Team Projects > Add new project > Import an existing project > GitHub."
step "Select the exact repository and production branch main. Keep netlify.toml's build and publish settings."
step "Choose the staging slug. A first build before environment setup must fail closed; do not accept a usable empty/PGLite app."
ask NETLIFY_PROJECT_SLUG "Netlify project slug (without .netlify.app):"
require_value NETLIFY_PROJECT_SLUG "$NETLIFY_PROJECT_SLUG"
[[ "$NETLIFY_PROJECT_SLUG" =~ ^[a-z0-9][a-z0-9-]*[a-z0-9]$ ]] ||
  stop "The Netlify slug must contain lowercase letters, digits, and hyphens."
NETLIFY_URL="https://${NETLIFY_PROJECT_SLUG}.netlify.app"
VITE_PUBLIC_HOSTNAME="${NETLIFY_PROJECT_SLUG}.netlify.app"
BETTER_AUTH_URL="$NETLIFY_URL"
ask NETLIFY_SITE_ID "Project configuration > General > Project information > Site ID:"
require_value NETLIFY_SITE_ID "$NETLIFY_SITE_ID"
write_env NETLIFY_PROJECT_SLUG "$NETLIFY_PROJECT_SLUG"
write_env NETLIFY_SITE_ID "$NETLIFY_SITE_ID"
write_env NETLIFY_URL "$NETLIFY_URL"
write_env VITE_PUBLIC_HOSTNAME "$VITE_PUBLIC_HOSTNAME"
write_env BETTER_AUTH_URL "$BETTER_AUTH_URL"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Netlify Ohio, deploy isolation, and private access"
open_url "https://app.netlify.com/sites/$NETLIFY_PROJECT_SLUG/configuration/deploys"
step "Project configuration > Build & deploy > Continuous deployment > Functions region: confirm cmh / US East (Ohio)."
step "Branches and deploy contexts > Configure: production branch main, Branch deploys None, Deploy Previews disabled."
step "Project configuration > General > Visitor access > Project visibility: keep this staging project Private."
confirm_or_stop "Are Functions in cmh Ohio, branch deploys off, Deploy Previews off, and staging Private?" \
  "Region, database isolation, and spend protection must be fixed before secrets are added."
write_env NETLIFY_FUNCTION_REGION "cmh"
write_env NETLIFY_DEPLOY_PREVIEWS "disabled"
write_env NETLIFY_PROJECT_VISIBILITY "private"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Stable auth secrets and exact callback mode"
generate_secret DAR_KEY_SECRET
generate_secret BETTER_AUTH_SECRET
generate_secret ARTIFACT_DELIVERY_SECRET
write_env VITE_AUTH_ENABLED "true"

say "Choose 'email' for email/password, or 'broker' for Google/X through a dedicated Grok broker client."
ask AUTH_MODE "Authentication mode (email or broker):"
case "$AUTH_MODE" in
  email)
    VITE_GROK_AUTH_ENABLED="false"
    remove_env GROK_AUTH_ISSUER
    remove_env GROK_AUTH_CLIENT_ID
    remove_env GROK_AUTH_CLIENT_SECRET
    remove_env GROK_GOOGLE_CALLBACK_URL
    remove_env GROK_X_CALLBACK_URL
    say "The Netlify login page must hide Google and X in this mode."
    ;;
  broker)
    VITE_GROK_AUTH_ENABLED="true"
    GROK_GOOGLE_CALLBACK_URL="$NETLIFY_URL/api/auth/oauth2/callback/grok-google"
    GROK_X_CALLBACK_URL="$NETLIFY_URL/api/auth/oauth2/callback/grok-x"
    say "Register exactly these callbacks with the broker operator:"
    say "$GROK_GOOGLE_CALLBACK_URL"
    say "$GROK_X_CALLBACK_URL"
    ask GROK_AUTH_ISSUER "Broker issuer (normally https://auth.grok.me):"
    require_value GROK_AUTH_ISSUER "$GROK_AUTH_ISSUER"
    [[ "$GROK_AUTH_ISSUER" == https://* ]] || stop "The broker issuer must be HTTPS."
    ask GROK_AUTH_CLIENT_ID "Dedicated Netlify app broker client ID:"
    require_value GROK_AUTH_CLIENT_ID "$GROK_AUTH_CLIENT_ID"
    ask_secret GROK_AUTH_CLIENT_SECRET "Dedicated Netlify app broker client secret:"
    require_value GROK_AUTH_CLIENT_SECRET "$GROK_AUTH_CLIENT_SECRET"
    write_env GROK_GOOGLE_CALLBACK_URL "$GROK_GOOGLE_CALLBACK_URL"
    write_env GROK_X_CALLBACK_URL "$GROK_X_CALLBACK_URL"
    write_env GROK_AUTH_ISSUER "$GROK_AUTH_ISSUER"
    write_env GROK_AUTH_CLIENT_ID "$GROK_AUTH_CLIENT_ID"
    write_env GROK_AUTH_CLIENT_SECRET "$GROK_AUTH_CLIENT_SECRET"
    ;;
  *) stop "AUTH_MODE must be exactly 'email' or 'broker'." ;;
esac
write_env AUTH_MODE "$AUTH_MODE"
write_env VITE_GROK_AUTH_ENABLED "$VITE_GROK_AUTH_ENABLED"

ask DAR_ADMIN_EMAILS "Optional comma-separated team-key admin emails (blank for none):"
write_optional DAR_ADMIN_EMAILS "$DAR_ADMIN_EMAILS"
if confirm "Configure Resend mail delivery now?"; then
  ask_secret RESEND_API_KEY "Resend API key:"
  require_value RESEND_API_KEY "$RESEND_API_KEY"
  ask EMAIL_FROM "Verified From address:"
  require_value EMAIL_FROM "$EMAIL_FROM"
  write_env RESEND_API_KEY "$RESEND_API_KEY"
  write_env EMAIL_FROM "$EMAIL_FROM"
else
  remove_env RESEND_API_KEY
  remove_env EMAIL_FROM
fi
if confirm "Configure the optional Netlify xAI platform key now?"; then
  ask_secret XAI_API_KEY "xAI API key:"
  require_value XAI_API_KEY "$XAI_API_KEY"
  write_env XAI_API_KEY "$XAI_API_KEY"
else
  remove_env XAI_API_KEY
fi
chmod 600 "$ENV_FILE"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Render Ohio Blueprint: worker and artifact gateway"
open_url "https://dashboard.render.com/"
say "Migration 0013 must already be verified. Render does not run database migrations."
step "New > Blueprint > Connect the exact repository; select branch main and path render.yaml."
step "Review dar-studio-worker: worker/docker, region ohio, plan 1c-2g, auto deploy off, one instance, max shutdown delay 300 seconds."
step "Review disk dar-studio-worker-data at /var/data, 10 GB. The paid disk disables zero-downtime deploys."
step "Review dar-studio-artifacts: web/docker, region ohio, plan 1c-2g, auto deploy off, one instance, health /healthz, max shutdown delay 300 seconds, no disk."
step "At the initial worker sync:false prompts enter pooled DATABASE_URL and EXA, JINA, PERPLEXITY, ANTHROPIC, OPENAI, and GEMINI keys."
step "For dar-studio-artifacts enter the same pooled DATABASE_URL, the generated ARTIFACT_DELIVERY_SECRET, and APP_ORIGIN=$NETLIFY_URL. Render supplies PORT; do not add it."
step "Do not enter MIGRATION_DATABASE_URL, DAR_KEY_SECRET, BETTER_AUTH_SECRET, broker values, or any other Netlify-only value."
warn "Render prompts for sync:false values only during initial Blueprint creation. Verify every key before deployment."
confirm_or_stop "Does the review exactly match both Ohio services, the one worker disk, main commit, and each service's required secrets?" \
  "Do not create mismatched or incompletely configured paid services."
confirm_or_stop "Deploy this billed Blueprint now?" \
  "The paid Render mutation was not authorized."
step "Click Deploy Blueprint and wait for both resources to be created."
step "Open the new Blueprint's Settings page and set Auto Sync to No. Service auto-deploy is already off in render.yaml."
confirm_or_stop "Are Blueprint Auto Sync and both services' automatic deploy triggers off?" \
  "A later repository push must not interrupt an active workflow or replace the reviewed gateway unexpectedly."
ask RENDER_BLUEPRINT_ID "Render Blueprint ID from its Settings page or URL:"
require_value RENDER_BLUEPRINT_ID "$RENDER_BLUEPRINT_ID"
ask RENDER_WORKER_SERVICE_ID "dar-studio-worker service ID from its Settings page or URL:"
require_value RENDER_WORKER_SERVICE_ID "$RENDER_WORKER_SERVICE_ID"
ask RENDER_ARTIFACT_SERVICE_ID "dar-studio-artifacts service ID from its Settings page or URL:"
require_value RENDER_ARTIFACT_SERVICE_ID "$RENDER_ARTIFACT_SERVICE_ID"
ask ARTIFACT_GATEWAY_URL "dar-studio-artifacts public HTTPS origin (no trailing slash):"
require_value ARTIFACT_GATEWAY_URL "$ARTIFACT_GATEWAY_URL"
[[ "$ARTIFACT_GATEWAY_URL" =~ ^https://[a-z0-9]([a-z0-9-]*[a-z0-9])?\.onrender\.com$ ]] ||
  stop "ARTIFACT_GATEWAY_URL must be the exact Render HTTPS origin with no path or trailing slash."
write_env RENDER_BLUEPRINT_ID "$RENDER_BLUEPRINT_ID"
write_env RENDER_BLUEPRINT_AUTO_SYNC "disabled"
write_env RENDER_WORKER_SERVICE_ID "$RENDER_WORKER_SERVICE_ID"
write_env RENDER_ARTIFACT_SERVICE_ID "$RENDER_ARTIFACT_SERVICE_ID"
write_env ARTIFACT_GATEWAY_URL "$ARTIFACT_GATEWAY_URL"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Render worker and artifact gateway verification"
open_url "https://dashboard.render.com/worker/$RENDER_WORKER_SERVICE_ID"
step "Open worker Logs. Require [worker-checkout] installed/reusing, [worker-preflight] ready, and [worker] host/pipeline/interpreter/watching queue lines."
step "Require DAMM commit 92c6ffe8b331347bc05f345785fe409753401a24, clean source, /var/data/checkouts/<commit>, and /opt/damm-venv/bin/python."
step "Require Pandoc, LibreOffice/soffice, six nonempty vendor variables with pinned SDK imports, blank mode-0600 upstream .env, and queue watching."
warn "Any worker-checkout, worker-preflight, or worker-entrypoint failed line, checkout drift, missing renderer/vendor, or crash loop is a hard stop."
open_url "$ARTIFACT_GATEWAY_URL/healthz"
step "Require gateway status 200, body {\"status\":\"ok\"}, and Cache-Control: no-store."
step "Request fixed $ARTIFACT_GATEWAY_URL/v1/artifacts without the exact Origin and Authorization header; require a non-disclosing 404 with body Not found."
open_url "https://dashboard.render.com/web/$RENDER_ARTIFACT_SERVICE_ID"
step "Open gateway Logs; require [artifact-gateway] listening on 0.0.0.0:<PORT> and no secret or database URL."
ask RENDER_WORKER_DEPLOY_ID "Successful Render worker deploy ID:"
require_value RENDER_WORKER_DEPLOY_ID "$RENDER_WORKER_DEPLOY_ID"
ask RENDER_WORKER_DEPLOY_SHA "Commit SHA shown for the worker deploy:"
[[ "$RENDER_WORKER_DEPLOY_SHA" == "$DEPLOY_GIT_SHA" ]] ||
  stop "The Render worker did not deploy the recorded origin/main commit."
ask RENDER_ARTIFACT_DEPLOY_ID "Successful Render artifact gateway deploy ID:"
require_value RENDER_ARTIFACT_DEPLOY_ID "$RENDER_ARTIFACT_DEPLOY_ID"
ask RENDER_ARTIFACT_DEPLOY_SHA "Commit SHA shown for the artifact gateway deploy:"
[[ "$RENDER_ARTIFACT_DEPLOY_SHA" == "$DEPLOY_GIT_SHA" ]] ||
  stop "The Render artifact gateway did not deploy the recorded origin/main commit."
write_env RENDER_WORKER_DEPLOY_ID "$RENDER_WORKER_DEPLOY_ID"
write_env RENDER_WORKER_DEPLOY_SHA "$RENDER_WORKER_DEPLOY_SHA"
write_env RENDER_ARTIFACT_DEPLOY_ID "$RENDER_ARTIFACT_DEPLOY_ID"
write_env RENDER_ARTIFACT_DEPLOY_SHA "$RENDER_ARTIFACT_DEPLOY_SHA"
confirm_or_stop "Are both services stable, on the exact commit, and free of preflight, health, or disclosure failures?" \
  "Do not expose Netlify or launch a workflow while either Render service is unverified."

# ── 13 ────────────────────────────────────────────────────────────────────
stage "Netlify production-only environment"
open_url "https://app.netlify.com/sites/$NETLIFY_PROJECT_SLUG/configuration/env"
warn "Do not import the whole $ENV_FILE file: it contains Render-only keys and values with different Netlify scopes."
step "Add pooled DATABASE_URL: Production context, Builds + Functions scopes, secret."
step "Add MIGRATION_DATABASE_URL from local DATABASE_URL_DIRECT: Production context, Builds scope only, secret."
step "Add DAR_KEY_SECRET, BETTER_AUTH_SECRET, and BETTER_AUTH_URL: Production, Builds + Functions. Mark both secrets."
step "Add ARTIFACT_GATEWAY_URL=$ARTIFACT_GATEWAY_URL and ARTIFACT_DELIVERY_SECRET: Production, Builds + Functions. Mark the secret."
step "Add VITE_AUTH_ENABLED=true and VITE_GROK_AUTH_ENABLED=$VITE_GROK_AUTH_ENABLED: Production, Builds + Functions."
step "Add VITE_PUBLIC_HOSTNAME=$VITE_PUBLIC_HOSTNAME: Production, Builds only."
if [[ "$AUTH_MODE" == "broker" ]]; then
  step "Add GROK_AUTH_ISSUER, GROK_AUTH_CLIENT_ID, and GROK_AUTH_CLIENT_SECRET: Production, Builds + Functions; mark the secret."
fi
[[ -n "$DAR_ADMIN_EMAILS" ]] && step "Add DAR_ADMIN_EMAILS: Production, Functions only."
[[ -n "${RESEND_API_KEY:-}" ]] && step "Add RESEND_API_KEY (secret) and EMAIL_FROM: Production, Functions only."
[[ -n "${XAI_API_KEY:-}" ]] && step "Add XAI_API_KEY: Production, Functions only, secret."
step "Confirm no database URL, auth secret, encryption key, broker value, artifact secret, mail key, or AI key has any Preview/branch/dev context."
confirm_or_stop "Does the Netlify environment list exactly match these keys, contexts, and scopes?" \
  "Incorrect scopes can leak staging data or make the build preflight silently invalid."
write_env NETLIFY_ENVIRONMENT_VERIFIED "true"

# ── 14 ────────────────────────────────────────────────────────────────────
stage "Netlify production deploy"
open_url "https://app.netlify.com/sites/$NETLIFY_PROJECT_SLUG/deploys"
step "Trigger a production deploy from main after every environment value is saved."
step "Require [deploy-preflight] success with Netlify CONTEXT=production and BRANCH=main, the migration advisory lock, and an up-to-date migration ledger."
step "Require the Netlify adapter output, not .vercel output. Open /, /methodology, and /login over HTTPS."
step "Confirm email auth works and Google/X visibility exactly matches VITE_GROK_AUTH_ENABLED."
step "Confirm app-owned loading, error, empty, dialog, and page states retain the explicit white background."
step "Confirm both artifact-gateway values reached Functions. The first authenticated JSON-grant and header-only byte-delivery proof occurs in Stage 16 after a real artifact exists."
ask NETLIFY_DEPLOY_ID "Successful Netlify production deploy ID:"
require_value NETLIFY_DEPLOY_ID "$NETLIFY_DEPLOY_ID"
ask NETLIFY_DEPLOY_SHA "Commit SHA shown for that deploy:"
[[ "$NETLIFY_DEPLOY_SHA" == "$DEPLOY_GIT_SHA" ]] ||
  stop "Netlify did not deploy the recorded origin/main commit."
write_env NETLIFY_DEPLOY_ID "$NETLIFY_DEPLOY_ID"
write_env NETLIFY_DEPLOY_SHA "$NETLIFY_DEPLOY_SHA"
confirm_or_stop "Did every web, configuration, and fail-closed check pass without a usable PGLite-backed deployment?" \
  "The web deployment is not ready for workflow smoke testing."

# ── 15 ────────────────────────────────────────────────────────────────────
stage "Three registered human identities"
open_url "$NETLIFY_URL/login"
say "Create three distinct Better Auth accounts. Store their passwords in your password manager; this wizard records names/emails only."
ask SMOKE_OWNER_NAME "Country owner / G3 signer name:"
require_value SMOKE_OWNER_NAME "$SMOKE_OWNER_NAME"
ask SMOKE_OWNER_EMAIL "Country owner email:"
require_email SMOKE_OWNER_EMAIL "$SMOKE_OWNER_EMAIL"
ask SMOKE_G1_NAME "G1 assessor name:"
require_value SMOKE_G1_NAME "$SMOKE_G1_NAME"
ask SMOKE_G1_EMAIL "G1 assessor email:"
require_email SMOKE_G1_EMAIL "$SMOKE_G1_EMAIL"
ask SMOKE_G2_NAME "Independent G2 reviewer name:"
require_value SMOKE_G2_NAME "$SMOKE_G2_NAME"
ask SMOKE_G2_EMAIL "Independent G2 reviewer email:"
require_email SMOKE_G2_EMAIL "$SMOKE_G2_EMAIL"
[[ "$SMOKE_OWNER_EMAIL" != "$SMOKE_G1_EMAIL" &&
   "$SMOKE_OWNER_EMAIL" != "$SMOKE_G2_EMAIL" &&
   "$SMOKE_G1_EMAIL" != "$SMOKE_G2_EMAIL" ]] ||
  stop "Owner, G1, and G2 must be three different registered accounts."
write_env SMOKE_OWNER_NAME "$SMOKE_OWNER_NAME"
write_env SMOKE_OWNER_EMAIL "$SMOKE_OWNER_EMAIL"
write_env SMOKE_G1_NAME "$SMOKE_G1_NAME"
write_env SMOKE_G1_EMAIL "$SMOKE_G1_EMAIL"
write_env SMOKE_G2_NAME "$SMOKE_G2_NAME"
write_env SMOKE_G2_EMAIL "$SMOKE_G2_EMAIL"
step "Sign out and sign back in as each account. Email verification is not required; password recovery is not proven without Resend."
confirm_or_stop "Did all three exact registered identities authenticate successfully?" \
  "Human controls cannot be tested with shared, demo, or unregistered identities."

# ── 16 ────────────────────────────────────────────────────────────────────
stage "Autonomous eight-stage Draft and artifact smoke"
warn "This stage consumes vendor budget. Country must be the only required launch input."
confirm_or_stop "Is a complete eight-stage staging workflow spend authorized now?" \
  "Do not launch without explicit vendor-spend authority."
step "As the owner, create one country, leave all optional upload categories empty, and click Launch Draft DAR workflow once."
step "Observe all eight stages. There must be no human input, review gate, pause, approval, or budget top-up."
step "At completion require Draft · pre-review and explicit wording that automation is not G1/G2/G3 or publication readiness."
step "Download the bundle, Draft MD/DOCX/PDF, cost-benefit XLSX, source XLSX, manifests, and representative artifacts from every stage."
step "Use the largest real artifact from this run: require Netlify 200 + no-store delivery-grant JSON, with a fixed HTTPS /v1/artifacts endpoint and no capability in any URL."
step "Require the browser to send the capability only as Authorization: Bearer, without cookies, from APP_ORIGIN; gateway must return 200, private/no-store, filename, length, SHA header, and an exact body hash."
step "Require anonymous/unassigned denial at Netlify. In an ephemeral history-free client, change one header capability character and replay a separate untouched header capability after >60 seconds; both gateway responses must be the same non-disclosing 404."
step "During G1 reassignment, require a previously minted but unexpired capability for the superseded reviewer to fail at the gateway immediately."
step "The repository suite proves an exact synthetic >20 MiB 21-chunk stream plus wrong-package and changed-hash rejection. If this run naturally exceeds 20 MiB, record its live size/hash proof too; never mutate staging rows or distort the country-only workflow to manufacture it."
ask SMOKE_COUNTRY_ID "Smoke country ID:"
require_value SMOKE_COUNTRY_ID "$SMOKE_COUNTRY_ID"
ask SMOKE_RUN_ID "Completed workflow run ID:"
require_value SMOKE_RUN_ID "$SMOKE_RUN_ID"
ask SMOKE_ARTIFACT_SET_ID "Immutable artifact-set ID:"
require_value SMOKE_ARTIFACT_SET_ID "$SMOKE_ARTIFACT_SET_ID"
ask SMOKE_BUNDLE_SHA256 "Complete-bundle SHA-256:"
require_sha256 SMOKE_BUNDLE_SHA256 "$SMOKE_BUNDLE_SHA256"
ask SMOKE_WORKFLOW_CONTRACT_SHA256 "Workflow contract SHA-256:"
require_sha256 SMOKE_WORKFLOW_CONTRACT_SHA256 "$SMOKE_WORKFLOW_CONTRACT_SHA256"
ask SMOKE_DAMM_MODEL_SHA256 "DAMM model SHA-256:"
require_sha256 SMOKE_DAMM_MODEL_SHA256 "$SMOKE_DAMM_MODEL_SHA256"
ask SMOKE_ASSESSMENT_INPUT_SHA256 "Assessment-input SHA-256:"
require_sha256 SMOKE_ASSESSMENT_INPUT_SHA256 "$SMOKE_ASSESSMENT_INPUT_SHA256"
ask SMOKE_BUNDLE_BYTES "Downloaded bundle byte count:"
[[ "$SMOKE_BUNDLE_BYTES" =~ ^[0-9]+$ && "$SMOKE_BUNDLE_BYTES" -gt 0 ]] ||
  stop "Bundle byte count must be a positive integer."
ask SMOKE_GATEWAY_ARTIFACT_BYTES "Largest real artifact verified through the gateway, in bytes:"
[[ "$SMOKE_GATEWAY_ARTIFACT_BYTES" =~ ^[0-9]+$ && "$SMOKE_GATEWAY_ARTIFACT_BYTES" -gt 0 ]] ||
  stop "The real gateway artifact byte count must be a positive integer."
if [[ "$SMOKE_GATEWAY_ARTIFACT_BYTES" -gt 20971520 ]]; then
  SMOKE_LIVE_OVER_20_MIB="true"
else
  SMOKE_LIVE_OVER_20_MIB="false"
  say "This real package stayed below 20 MiB; the mandatory synthetic 21-chunk regression is the large-stream proof."
fi
write_env SMOKE_COUNTRY_ID "$SMOKE_COUNTRY_ID"
write_env SMOKE_RUN_ID "$SMOKE_RUN_ID"
write_env SMOKE_ARTIFACT_SET_ID "$SMOKE_ARTIFACT_SET_ID"
write_env SMOKE_BUNDLE_SHA256 "$SMOKE_BUNDLE_SHA256"
write_env SMOKE_WORKFLOW_CONTRACT_SHA256 "$SMOKE_WORKFLOW_CONTRACT_SHA256"
write_env SMOKE_DAMM_MODEL_SHA256 "$SMOKE_DAMM_MODEL_SHA256"
write_env SMOKE_ASSESSMENT_INPUT_SHA256 "$SMOKE_ASSESSMENT_INPUT_SHA256"
write_env SMOKE_BUNDLE_BYTES "$SMOKE_BUNDLE_BYTES"
write_env SMOKE_GATEWAY_ARTIFACT_BYTES "$SMOKE_GATEWAY_ARTIFACT_BYTES"
write_env SMOKE_LIVE_OVER_20_MIB "$SMOKE_LIVE_OVER_20_MIB"
confirm_or_stop "Did every workflow, lifecycle, persistence, format, download, hash, and white-background check pass?" \
  "The completed Draft package did not satisfy staging acceptance."

# ── 17 ────────────────────────────────────────────────────────────────────
stage "Post-completion G1, G2, and G3"
open_url "$NETLIFY_URL"
step "As owner open Human controls. Before assignments require zero human decisions and a locked G3."
step "Temporarily assign pending G1 to $SMOKE_G2_EMAIL. Require its exact-package download access, while the still-unassigned $SMOKE_G1_EMAIL account is denied."
step "Replace that pending G1 assignment with $SMOKE_G1_EMAIL and a reason. Require the superseded account's new artifact request to be denied and the immutable supersession audit to remain visible."
step "Assign G2 to $SMOKE_G2_EMAIL. Require exact-package access again. Attempt to replace G2 with the active G1 account and require rejection."
step "Open G2 before G1: its frozen scope may be visible, but submission must be locked."
step "As G1 decide every machine-filled row, affirm the human role, and record the immutable G1 decision. Reopen it read-only."
step "As the distinct G2 reviewer independently decide every frozen-scope row, affirm, and record G2."
step "As owner confirm G3 unlocks only now, check all seven affirmations, and record the named/dated decision."
step "Require a versioned Approved Draft release; the unratified methodology must never yield Canonical Final. Original Draft downloads must remain unchanged."
ask SMOKE_PACKAGE_ID "Approval package ID:"
require_value SMOKE_PACKAGE_ID "$SMOKE_PACKAGE_ID"
ask SMOKE_TARGET_IDENTITY_SHA256 "Approval target-identity SHA-256:"
require_sha256 SMOKE_TARGET_IDENTITY_SHA256 "$SMOKE_TARGET_IDENTITY_SHA256"
ask SMOKE_G1_DECISION_ID "Immutable G1 decision ID:"
require_value SMOKE_G1_DECISION_ID "$SMOKE_G1_DECISION_ID"
ask SMOKE_G2_DECISION_ID "Immutable G2 decision ID:"
require_value SMOKE_G2_DECISION_ID "$SMOKE_G2_DECISION_ID"
ask SMOKE_G3_DECISION_ID "Immutable G3 decision ID:"
require_value SMOKE_G3_DECISION_ID "$SMOKE_G3_DECISION_ID"
ask SMOKE_RELEASE_ID "Versioned Approved Draft release ID:"
require_value SMOKE_RELEASE_ID "$SMOKE_RELEASE_ID"
write_env SMOKE_PACKAGE_ID "$SMOKE_PACKAGE_ID"
write_env SMOKE_TARGET_IDENTITY_SHA256 "$SMOKE_TARGET_IDENTITY_SHA256"
write_env SMOKE_G1_DECISION_ID "$SMOKE_G1_DECISION_ID"
write_env SMOKE_G2_DECISION_ID "$SMOKE_G2_DECISION_ID"
write_env SMOKE_G3_DECISION_ID "$SMOKE_G3_DECISION_ID"
write_env SMOKE_RELEASE_ID "$SMOKE_RELEASE_ID"
confirm_or_stop "Were G2 independence, early-G3 lock, immutable identities, Draft preservation, and honest release wording all enforced?" \
  "The human-control chain failed live acceptance."

# ── 18 ────────────────────────────────────────────────────────────────────
stage "Neon audit, immutability probe, and closeout"
open_url "https://console.neon.tech/app/projects/$NEON_PROJECT_ID"
step "In SQL Editor run the package/decision/release audit query from the deployment guide using $SMOKE_PACKAGE_ID."
step "Require three human actors, distinct G1/G2 user IDs, owner G3, one exact package/bundle identity, model_ratified=false, lifecycle approved_draft."
step "Run the assignment/supersession query. Require one inactive temporary G1 with one immutable supersession, plus the intended active completed G1 and independent G2."
step "Run the guide's zero-persistence DO-block update probe against G1 decision $SMOKE_G1_DECISION_ID. Require the immutable trigger, then re-query the unchanged identity."
step "Record the Netlify deploy and both separate Render service deploy IDs/commits, Neon project/branch/snapshot, run/package hashes, decision/release IDs, validation results, and UTC completion time."
step "Keep the pre-migration snapshot through acceptance. Rollback order is: block launches, settle runs, suspend both Render services, publish/lock the prior web deploy, then restore Neon only with explicit data-loss authority."
confirm_or_stop "Did the database audit and immutable identity probe pass exactly?" \
  "Do not close staging acceptance with an incomplete audit."
DEPLOYMENT_ACCEPTED_AT_UTC=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
write_env DEPLOYMENT_ACCEPTED_AT_UTC "$DEPLOYMENT_ACCEPTED_AT_UTC"
write_env DEPLOYMENT_READINESS_STATUS "accepted-staging"
chmod 600 "$ENV_FILE"

finish
say "Deployment evidence is in $ENV_FILE (mode 0600, gitignored)."
say "Keep staging Private. This acceptance does not claim DAMM ratification or a canonical Final release."
