/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as ReviewAssignmentIdRouteImport } from './routes/review.$assignmentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRunsRunIdArtifactRouteImport } from './routes/api/runs/$runId.artifact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewAssignmentIdRoute = ReviewAssignmentIdRouteImport.update({
  id: '/review/$assignmentId',
  path: '/review/$assignmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdArtifactRoute = ApiRunsRunIdArtifactRouteImport.update({
  id: '/api/runs/$runId/artifact',
  path: '/api/runs/$runId/artifact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/c/$id': typeof CIdRoute
  '/review/$assignmentId': typeof ReviewAssignmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/runs/$runId/artifact': typeof ApiRunsRunIdArtifactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/c/$id': typeof CIdRoute
  '/review/$assignmentId': typeof ReviewAssignmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/runs/$runId/artifact': typeof ApiRunsRunIdArtifactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/c/$id': typeof CIdRoute
  '/review/$assignmentId': typeof ReviewAssignmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/runs/$runId/artifact': typeof ApiRunsRunIdArtifactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/methodology'
    | '/reset-password'
    | '/settings'
    | '/c/$id'
    | '/review/$assignmentId'
    | '/api/auth/$'
    | '/api/runs/$runId/artifact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/methodology'
    | '/reset-password'
    | '/settings'
    | '/c/$id'
    | '/review/$assignmentId'
    | '/api/auth/$'
    | '/api/runs/$runId/artifact'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/methodology'
    | '/reset-password'
    | '/settings'
    | '/c/$id'
    | '/review/$assignmentId'
    | '/api/auth/$'
    | '/api/runs/$runId/artifact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  CIdRoute: typeof CIdRoute
  ReviewAssignmentIdRoute: typeof ReviewAssignmentIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRunsRunIdArtifactRoute: typeof ApiRunsRunIdArtifactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$assignmentId': {
      id: '/review/$assignmentId'
      path: '/review/$assignmentId'
      fullPath: '/review/$assignmentId'
      preLoaderRoute: typeof ReviewAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/artifact': {
      id: '/api/runs/$runId/artifact'
      path: '/api/runs/$runId/artifact'
      fullPath: '/api/runs/$runId/artifact'
      preLoaderRoute: typeof ApiRunsRunIdArtifactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  CIdRoute: CIdRoute,
  ReviewAssignmentIdRoute: ReviewAssignmentIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRunsRunIdArtifactRoute: ApiRunsRunIdArtifactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
